// SPDX-FileCopyrightText: 2026 Ángel Guzmán Maeso <angel@guzmanmaeso.com>
// SPDX-License-Identifier: MIT
/**
 * A second application holding two of everything, for the security,
 * messenger, validator and Twig side.
 */

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

let root: string;
let app: string;

const FILES: Record<string, string> = {
  'composer.json': JSON.stringify({
    require: {
      'symfony/framework-bundle': '^7.0',
      'symfony/messenger': '^7.0',
      'symfony/notifier': '^7.0',
      'symfony/validator': '^7.0',
      'symfony/twig-bundle': '^7.0',
      'symfony/security-bundle': '^7.0',
    },
  }, null, 2) + '\n',

  'config/packages/security.yaml': [
    'security:',
    '    password_hashers:',
    '        App\\Entity\\User:',
    '            algorithm: auto',
    '            migrate_from: [bcrypt, md5]',
    '        App\\Entity\\Admin:',
    '            algorithm: sodium',
    '            migrate_from: [bcrypt]',
    '    providers:',
    '        users:',
    '            entity: { class: App\\Entity\\User, property: email }',
    '        admins:',
    '            entity: { class: App\\Entity\\Admin, property: email }',
    '    firewalls:',
    '        main:',
    '            provider: users',
    '            entry_point: App\\Security\\FormEntryPoint',
    '            custom_authenticators:',
    '                - App\\Security\\TokenAuthenticator',
    '                - App\\Security\\LinkAuthenticator',
    '            remember_me:',
    '                secret: "%kernel.secret%"',
    '                lifetime: 31536000',
    '                secure: false',
    '            login_link:',
    '                check_route: login_check',
    '                signature_properties: [id]',
    '                lifetime: 86400',
    '                max_uses: 10',
        '        admin:',
    '            provider: admins',
    '            entry_point: App\\Security\\ApiEntryPoint',
    '            custom_authenticators: [App\\Security\\ApiAuthenticator]',
    '            remember_me:',
    '                secret: "%kernel.secret%"',
    '                lifetime: 604800',
    '            login_link:',
    '                check_route: admin_login_check',
    '                signature_properties: [id, email]',
    '                lifetime: 300',
    '                max_uses: 1',
    '    access_control:',
    '        - { path: ^/admin, roles: ROLE_ADMIN }',
    '        - { path: ^/orders, roles: ORDER_VIEW }',
    '        - { path: ^/invoices, roles: INVOICE_DOWNLOAD }',
  ].join('\n') + '\n',

  'src/Security/FormEntryPoint.php': [
    '<?php',
    'namespace App\\Security;',
    '',
    'use Symfony\\Component\\HttpFoundation\\RedirectResponse;',
    'use Symfony\\Component\\HttpFoundation\\Request;',
    'use Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException;',
    'use Symfony\\Component\\Security\\Http\\EntryPoint\\AuthenticationEntryPointInterface;',
    '',
    'class FormEntryPoint implements AuthenticationEntryPointInterface',
    '{',
    '    public function start(Request $request, ?AuthenticationException $exception = null): RedirectResponse',
    '    {',
    '        return new RedirectResponse("/login");',
    '    }',
    '}',
  ].join('\n') + '\n',

  'src/Security/ApiEntryPoint.php': [
    '<?php',
    'namespace App\\Security;',
    '',
    'use Symfony\\Component\\HttpFoundation\\JsonResponse;',
    'use Symfony\\Component\\HttpFoundation\\Request;',
    'use Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException;',
    'use Symfony\\Component\\Security\\Http\\EntryPoint\\AuthenticationEntryPointInterface;',
    '',
    'class ApiEntryPoint implements AuthenticationEntryPointInterface',
    '{',
    '    public function start(Request $request, ?AuthenticationException $exception = null): JsonResponse',
    '    {',
    '        return new JsonResponse(["error" => "unauthenticated"], 401);',
    '    }',
    '}',
  ].join('\n') + '\n',

  'src/Security/Voter/OrderVoter.php': [
    '<?php',
    'namespace App\\Security\\Voter;',
    '',
    'use Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface;',
    'use Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter;',
    '',
    'class OrderVoter extends Voter',
    '{',
    '    protected function supports(string $attribute, mixed $subject): bool',
    '    {',
    '        return in_array($attribute, ["ORDER_VIEW", "ORDER_EDIT"], true);',
    '    }',
    '',
    '    protected function voteOnAttribute(string $attribute, mixed $subject, TokenInterface $token): bool',
    '    {',
    '        return true;',
    '    }',
    '}',
  ].join('\n') + '\n',

  'src/Security/Voter/InvoiceVoter.php': [
    '<?php',
    'namespace App\\Security\\Voter;',
    '',
    'use Symfony\\Component\\Security\\Core\\Authentication\\Token\\TokenInterface;',
    'use Symfony\\Component\\Security\\Core\\Authorization\\Voter\\Voter;',
    '',
    'class InvoiceVoter extends Voter',
    '{',
    '    protected function supports(string $attribute, mixed $subject): bool',
    '    {',
    '        return $attribute === "INVOICE_VIEW";',
    '    }',
    '',
    '    protected function voteOnAttribute(string $attribute, mixed $subject, TokenInterface $token): bool',
    '    {',
    '        return false;',
    '    }',
    '}',
  ].join('\n') + '\n',

  'src/Repository/UserRepository.php': [
    '<?php',
    'namespace App\\Repository;',
    '',
    'use Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository;',
    'use Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface;',
    'use Symfony\\Component\\Security\\Core\\User\\PasswordUpgraderInterface;',
    '',
    'class UserRepository extends ServiceEntityRepository implements PasswordUpgraderInterface',
    '{',
    '    public function upgradePassword(PasswordAuthenticatedUserInterface $user, string $newHashedPassword): void',
    '    {',
    '        $user->setPassword($newHashedPassword);',
    '        $this->getEntityManager()->flush();',
    '    }',
    '}',
  ].join('\n') + '\n',

  'src/Repository/AdminRepository.php': [
    '<?php',
    'namespace App\\Repository;',
    '',
    'use Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository;',
    'use Symfony\\Component\\Security\\Core\\User\\PasswordAuthenticatedUserInterface;',
    'use Symfony\\Component\\Security\\Core\\User\\PasswordUpgraderInterface;',
    '',
    'class AdminRepository extends ServiceEntityRepository implements PasswordUpgraderInterface',
    '{',
    '    public function upgradePassword(PasswordAuthenticatedUserInterface $user, string $newHashedPassword): void',
    '    {',
    '    }',
    '}',
  ].join('\n') + '\n',

  'config/packages/messenger.yaml': [
    'framework:',
    '    messenger:',
    '        failure_transport: failed',
    '        transports:',
    '            async:',
    '                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"',
    '                failure_transport: failed',
    '                options:',
    '                    queue_name: default',
    '            async_high:',
    '                dsn: "amqp://guest:guest@rabbitmq:5672/%2f/high"',
    '                failure_transport: failed_high',
    '                options:',
    '                    lock: true',
    '            low_priority:',
    '                dsn: "doctrine://default?queue_name=low"',
    '            failed:',
    '                dsn: "doctrine://default?queue_name=failed"',
    '            failed_high:',
    '                dsn: "doctrine://default?queue_name=failed_high"',
    '            dead_letter:',
    '                dsn: "doctrine://default?queue_name=dead"',
    '            second_dead_letter:',
    '                dsn: "doctrine://default?queue_name=dead2"',
    '        buses:',
    '            command.bus:',
    '                middleware: [validation, doctrine_transaction]',
    '            query.bus:',
    '                middleware: [validation]',
    '        routing:',
    '            "App\\Message\\First": async',
    '            "App\\Message\\Second": async_high',
  ].join('\n') + '\n',

  'config/packages/notifier.yaml': [
    'framework:',
    '    notifier:',
    '        chatter_transports:',
    '            slack: "slack://TOKEN0123456789@default?channel=alerts"',
    '            telegram: "telegram://0123456789:AAAAaaaaBBBBccccDDDD@default?channel=@acme"',
    '        texter_transports:',
    '            twilio: "twilio://SID0123:TOKEN4567@default?from=%2B34600000000"',
    '            vonage: "vonage://KEY0123:SECRET4567@default?from=Acme"',
    '        channel_policy:',
    '            urgent: ["chat/slack", "sms/twilio"]',
    '            high: ["chat/telegram"]',
    '        admin_recipients:',
    '            - { email: ops@example.com, phone: "+34600000000" }',
    '            - { email: oncall@example.com, phone: "+34600000001" }',
  ].join('\n') + '\n',

  'src/Entity/User.php': [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    'use Symfony\\Component\\Validator\\Constraints as Assert;',
    'use Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity;',
    '',
    '#[ORM\\Entity(repositoryClass: \\App\\Repository\\UserRepository::class)]',
    "#[UniqueEntity(fields: ['email'], message: 'Taken')]",
    "#[UniqueEntity(fields: ['id'])]",
    '#[Assert\\GroupSequence(["User", "Strict"])]',
    'class User',
    '{',
    '    #[ORM\\Id]',
    '    #[ORM\\GeneratedValue]',
    '    #[ORM\\Column]',
    '    private ?int $id = null;',
    '',
    '    #[ORM\\Column(length: 180, unique: true)]',
    '    #[Assert\\NotBlank(groups: ["Strict"])]',
    '    #[Assert\\Email]',
    '    private string $email = "";',
    '',
    '    #[Assert\\PasswordStrength(minScore: 2)]',
    '    #[Assert\\NotCompromisedPassword]',
    '    private string $plainPassword = "";',
    '',
    '    #[Assert\\Valid]',
    '    #[ORM\\OneToMany(targetEntity: Address::class, mappedBy: "user")]',
    '    private $addresses;',
    '',
    '    #[ORM\\ManyToOne(targetEntity: Address::class)]',
    '    private ?Address $mainAddress = null;',
    '',
    '    #[ORM\\Column(length: 32)]',
    '    private string $reference = "";',
    '}',
  ].join('\n') + '\n',

  'src/Entity/Admin.php': [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    'use Symfony\\Component\\Validator\\Constraints as Assert;',
    'use Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity;',
    '',
    '#[ORM\\Entity(repositoryClass: \\App\\Repository\\AdminRepository::class)]',
    "#[UniqueEntity(fields: ['email', 'tenant'])]",
    '#[Assert\\GroupSequence(["Admin", "Undeclared"])]',
    'class Admin',
    '{',
    '    #[ORM\\Id]',
    '    #[ORM\\GeneratedValue]',
    '    #[ORM\\Column]',
    '    private ?int $id = null;',
    '',
    '    #[ORM\\Column(length: 180)]',
    '    #[Assert\\NotBlank]',
    '    private string $email = "";',
    '',
    '    #[Assert\\PasswordStrength]',
    '    private string $plainPassword = "";',
    '',
    '    #[ORM\\ManyToOne(targetEntity: Address::class)]',
    '    private ?Address $address = null;',
    '}',
  ].join('\n') + '\n',

  'src/Entity/Address.php': [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    '',
    '#[ORM\\Entity]',
    'class Address',
    '{',
    '    #[ORM\\Id]',
    '    #[ORM\\GeneratedValue]',
    '    #[ORM\\Column]',
    '    private ?int $id = null;',
    '}',
  ].join('\n') + '\n',

  'src/Form/FirstType.php': [
    '<?php',
    'namespace App\\Form;',
    '',
    'use Symfony\\Component\\Form\\AbstractType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType;',
    'use Symfony\\Component\\Form\\FormBuilderInterface;',
    'use Symfony\\Component\\Form\\FormEvent;',
    'use Symfony\\Component\\Form\\FormEvents;',
    '',
    'class FirstType extends AbstractType',
    '{',
    '    public function buildForm(FormBuilderInterface $builder, array $options): void',
    '    {',
    '        $builder',
    '            ->add("plainPassword", RepeatedType::class, [',
    '                "type" => PasswordType::class,',
    '                "first_options" => ["label" => "Password"],',
    '                "second_options" => ["label" => "Repeat"],',
    '            ])',
    '            ->add("country", ChoiceType::class, [',
    '                "choices" => ["Spain" => "ES", "France" => "FR"],',
    '                "choice_value" => "code",',
    '            ]);',
    '',
    '        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) { });',
    '        $builder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) { });',
    '    }',
    '}',
  ].join('\n') + '\n',

  'src/Form/SecondType.php': [
    '<?php',
    'namespace App\\Form;',
    '',
    'use Symfony\\Component\\Form\\AbstractType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType;',
    'use Symfony\\Component\\Form\\FormBuilderInterface;',
    'use Symfony\\Component\\Form\\FormEvent;',
    'use Symfony\\Component\\Form\\FormEvents;',
    '',
    'class SecondType extends AbstractType',
    '{',
    '    public function buildForm(FormBuilderInterface $builder, array $options): void',
    '    {',
    '        $builder',
    '            ->add("email", RepeatedType::class, ["type" => \\Symfony\\Component\\Form\\Extension\\Core\\Type\\EmailType::class])',
    '            ->add("status", ChoiceType::class, ["choices" => ["Open" => 1, "Closed" => 2]]);',
    '',
    '        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) { }, 10);',
    '    }',
    '}',
  ].join('\n') + '\n',

  'templates/first.html.twig': [
    '{{ first_value|raw }}',
    '{{ include(dynamic_first) }}',
    '{% if is_granted("ORDER_VIEW") %}ok{% endif %}',
  ].join('\n') + '\n',

  'templates/second.html.twig': [
    '{{ second_value|raw }}',
    '{{ include(dynamic_second) }}',
    '{{ render(controller("App\\\\Controller\\\\FirstApiController::list")) }}',
    '{{ render(path("app_home")) }}',
  ].join('\n') + '\n',

  'src/Twig/FirstExtension.php': [
    '<?php',
    'namespace App\\Twig;',
    '',
    'use Twig\\Extension\\AbstractExtension;',
    'use Twig\\TwigFilter;',
    'use Twig\\TwigFunction;',
    'use Twig\\TwigTest;',
    '',
    'class FirstExtension extends AbstractExtension',
    '{',
    '    public function getFilters(): array',
    '    {',
    '        return [new TwigFilter("first_filter", [$this, "first"]), new TwigFilter("second_filter", [$this, "second"])];',
    '    }',
    '',
    '    public function getFunctions(): array',
    '    {',
    '        return [new TwigFunction("first_fn", [$this, "first"]), new TwigFunction("second_fn", [$this, "second"])];',
    '    }',
    '',
    '    public function getTests(): array',
    '    {',
    '        return [new TwigTest("first_test", [$this, "first"]), new TwigTest("second_test", [$this, "second"])];',
    '    }',
    '',
    '    public function getGlobals(): array',
    '    {',
    '        return ["first_global" => "a", "second_global" => "b"];',
    '    }',
    '',
    '    public function first(): string { return "a"; }',
    '    public function second(): string { return "b"; }',
    '}',
  ].join('\n') + '\n',

  'assets/controllers/first_controller.js': [
    "import { Controller } from '@hotwired/stimulus';",
    '',
    'export default class extends Controller {',
    "    static targets = ['output', 'input'];",
    "    static values = { url: String, count: Number };",
    "    static outlets = ['second-controller', 'third-controller'];",
    '',
    '    connect() {',
    '        this.outputTarget.textContent = this.urlValue;',
    '        this.secondControllerOutlet.refresh();',
    '    }',
    '}',
  ].join('\n') + '\n',

  'assets/controllers/second_controller.js': [
    "import { Controller } from '@hotwired/stimulus';",
    '',
    'export default class extends Controller {',
    "    static targets = ['panel'];",
    "    static values = { open: Boolean };",
    "    static outlets = ['first-controller'];",
    '',
    '    refresh() {',
    '        this.panelTarget.hidden = !this.openValue;',
    '    }',
    '}',
  ].join('\n') + '\n',

  'translations/messages.en.yaml': [
    'cart.items: "{count, plural, one {# item} other {# items}}"',
    'cart.legacy: "One item|%count% items"',
    'order.state: "Open"',
  ].join('\n') + '\n',

  'translations/messages.es.yaml': [
    'cart.items: "{count, plural, one {# artículo} few {# artículos} other {# artículos}}"',
    'cart.legacy: "Un artículo|%count% artículos|Muchos"',
    'order.state: "Abierto"',
  ].join('\n') + '\n',

  'translations/messages.fr.po': [
    'msgid ""',
    'msgstr ""',
    '"Content-Type: text/plain; charset=UTF-8\\n"',
    '',
    'msgid "order.state"',
    'msgstr "Ouvert"',
    '',
    'msgid "cart.legacy"',
    'msgstr "Un article"',
  ].join('\n') + '\n',

  '.env': [
    'APP_ENV=prod',
    'MESSENGER_TRANSPORT_DSN=doctrine://default',
    'DATABASE_URL=postgresql://acme:hunter2@db:5432/acme',
    'MAILER_DSN=smtp://acme:hunter2@smtp.example.com:25',
  ].join('\n') + '\n',

  '.env.example': [
    'APP_ENV=dev',
    'MESSENGER_TRANSPORT_DSN=',
    'DATABASE_URL=',
    'MAILER_DSN=',
    'SENTRY_DSN=',
    'REDIS_URL=',
  ].join('\n') + '\n',

  'src/Tests/FirstFunctionalTest.php': [
    '<?php',
    'namespace App\\Tests;',
    '',
    'use Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase;',
    '',
    'class FirstFunctionalTest extends WebTestCase',
    '{',
    '    public function testFirst(): void',
    '    {',
    '        $client = static::createClient();',
    '        $client->request("GET", "/");',
    '        $this->assertResponseIsSuccessful();',
    '    }',
    '',
    '    public function testSecond(): void',
    '    {',
    '        $client = static::createClient();',
    '        static::ensureKernelShutdown();',
    '        $client->request("GET", "/orders");',
    '    }',
    '}',
  ].join('\n') + '\n',

  'tests/SecondFunctionalTest.php': [
    '<?php',
    'namespace App\\Tests;',
    '',
    'use Symfony\\Bundle\\FrameworkBundle\\Test\\WebTestCase;',
    '',
    'class SecondFunctionalTest extends WebTestCase',
    '{',
    '    public function testWithoutShutdown(): void',
    '    {',
    '        $client = static::createClient();',
    '        $client->request("GET", "/api/first");',
    '        $second = static::createClient();',
    '    }',
    '}',
  ].join('\n') + '\n',

  'config/packages/html_sanitizer.yaml': [
    'framework:',
    '    html_sanitizer:',
    '        sanitizers:',
    '            app.comment:',
    '                allow_safe_elements: true',
    '                allow_elements:',
    '                    a: ["href"]',
    '                force_https_urls: false',
    '            app.description:',
    '                allow_safe_elements: false',
    '                block_elements: ["script"]',
    '                max_input_length: 100000',
  ].join('\n') + '\n',

  'config/packages/framework.yaml': [
    'framework:',
    '    semaphore:',
    '        first: "redis://localhost:6379"',
    '        second: "%env(REDIS_URL)%"',
    '    lock:',
    '        default: "flock"',
    '        invoice: "redis://localhost:6379"',
    '    http_client:',
    '        scoped_clients:',
    '            first.client:',
    '                base_uri: "https://first.example.com"',
    '                headers:',
    '                    Authorization: "Bearer 0123456789abcdef"',
    '            second.client:',
    '                base_uri: "https://second.example.com"',
    '                headers:',
    '                    X-Api-Key: "0123456789abcdef"',
  ].join('\n') + '\n',
};

beforeAll(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'symfony-pairs2-'));
  app = path.join(root, 'app');
  for (const [rel, content] of Object.entries(FILES)) {
    const full = path.join(app, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  }
});

afterAll(() => {
  fs.rmSync(root, { recursive: true, force: true });
});

async function runModule(name: string, extras: string[] = []): Promise<string> {
  const mod = await import(path.resolve(__dirname, '../tools', name)) as Record<string, unknown>;
  const texts: string[] = [];

  for (const [, value] of Object.entries(mod)) {
    if (typeof value !== 'function') continue;
    const fn = value as (...args: unknown[]) => unknown;
    if (fn.length === 0) continue;

    const argsets = fn.length === 1 ? [[app]] : extras.map((e) => [app, e, e]);
    for (const args of argsets) {
      const returned = await Promise.resolve(fn(...args.slice(0, fn.length)));
      expect(returned).toBeDefined();
      if (returned && typeof returned === 'object' && 'content' in returned) {
        const content = (returned as { content: Array<{ text?: string }> }).content;
        expect(Array.isArray(content)).toBe(true);
        texts.push(content.map((c) => c.text ?? '').join('\n'));
      }
    }
  }

  return texts.join('\n');
}

describe('two of everything, the security and messenger side', () => {
  test.each([
    ['symfony-security-entry-point', []],
    ['symfony-security-firewalls', []],
    ['symfony-security-login-link', []],
    ['symfony-security-remember-me', []],
    ['symfony-security-password-upgrade', []],
    ['symfony-security-custom-voter', []],
    ['symfony-password-migrator', []],
    ['symfony-password-strength', []],
    ['symfony-messenger-failures', []],
    ['symfony-messenger-priority', []],
    ['symfony-message-buses', []],
    ['symfony-notifier-channels', []],
    ['symfony-notifier-sms', []],
    ['symfony-validator-cascade', []],
    ['symfony-validator-group-sequence', []],
    ['symfony-validator-unique-entity', []],
    ['symfony-form-events', []],
    ['symfony-form-repeated', []],
    ['symfony-form-choice-value', []],
    ['symfony-twig-security', []],
    ['symfony-subrequest', []],
    ['twig-extensions', []],
    ['symfony-ux-stimulus-controllers', []],
    ['symfony-ux-stimulus-values', []],
    ['symfony-translation-plurals', []],
    ['symfony-translation-gaps', []],
    ['symfony-html-sanitizer', []],
    ['symfony-semaphore', []],
    ['symfony-http-client-auth', []],
    ['symfony-test-http-kernel', []],
    ['symfony-enlighten-analysis', []],
    ['symfony-lazy-services', []],
    ['symfony-cache-chain', []],
    ['symfony-domain-events', []],
    ['translations', ['messages', 'en']],
  ])('%s reports on the second pair application', async (name, extras) => {
    const text = await runModule(name, extras as string[]);
    expect(typeof text).toBe('string');
  });
});
