// SPDX-FileCopyrightText: 2026 Ángel Guzmán Maeso <angel@guzmanmaeso.com>
// SPDX-License-Identifier: MIT
/**
 * A ninth batch, written from the exact shapes the remaining parsers look
 * for: API Platform operations with their groups and security, a PHPUnit
 * coverage block with thresholds, Grafana dashboards, gRPC service
 * definitions, Behat step definitions, an asset pipeline and repositories
 * with the query shapes the analyser scores.
 */

import * as fs from 'fs';
import * as path from 'path';

function put(root: string, rel: string, content: string): void {
  const full = path.join(root, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

function apiAndTests(root: string): void {
  put(root, 'src/ApiResource/Invoice.php', [
    '<?php',
    'namespace App\\ApiResource;',
    '',
    'use ApiPlatform\\Metadata\\ApiResource;',
    'use ApiPlatform\\Metadata\\Delete;',
    'use ApiPlatform\\Metadata\\Get;',
    'use ApiPlatform\\Metadata\\GetCollection;',
    'use ApiPlatform\\Metadata\\Patch;',
    'use ApiPlatform\\Metadata\\Post;',
    'use Symfony\\Component\\Serializer\\Annotation\\Groups;',
    '',
    '#[ApiResource(',
    '    types: ["https://schema.org/Invoice"],',
    '    operations: [',
    '        new GetCollection(uriTemplate: "/invoices", normalizationContext: ["groups" => ["invoice:list"]], paginationItemsPerPage: 30),',
    '        new Get(uriTemplate: "/invoices/{id}", normalizationContext: ["groups" => ["invoice:read", "invoice:detail"]], security: "is_granted(\'ROLE_USER\')"),',
    '        new Post(uriTemplate: "/invoices", denormalizationContext: ["groups" => ["invoice:write"]], security: "is_granted(\'ROLE_ACCOUNTING\')", validationContext: ["groups" => ["Default", "create"]]),',
    '        new Patch(uriTemplate: "/invoices/{id}", denormalizationContext: ["groups" => ["invoice:write"]]),',
    '        new Delete(uriTemplate: "/invoices/{id}", security: "is_granted(\'ROLE_ADMIN\')"),',
    '    ],',
    '    normalizationContext: ["groups" => ["invoice:read"]],',
    '    denormalizationContext: ["groups" => ["invoice:write"]],',
    '    paginationEnabled: true,',
    '    paginationClientItemsPerPage: true,',
    '    order: ["issuedAt" => "DESC"],',
    ')]',
    'class Invoice',
    '{',
    '    #[Groups(["invoice:read", "invoice:list"])]',
    '    public int $id = 0;',
    '',
    '    #[Groups(["invoice:read", "invoice:write"])]',
    '    public string $reference = "";',
    '',
    '    #[Groups(["invoice:detail"])]',
    '    public array $lines = [];',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/ApiResource/PublicFeed.php', [
    '<?php',
    'namespace App\\ApiResource;',
    '',
    'use ApiPlatform\\Metadata\\ApiResource;',
    'use ApiPlatform\\Metadata\\GetCollection;',
    '',
    '#[ApiResource(',
    '    types: ["http://schema.org/DataFeed"],',
    '    operations: [new GetCollection(uriTemplate: "/feed")],',
    '    paginationEnabled: false,',
    ')]',
    'class PublicFeed',
    '{',
    '    public array $items = [];',
    '}',
  ].join('\n') + '\n');

  const phpunitXml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
    '         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"',
    '         bootstrap="tests/bootstrap.php"',
    '         cacheDirectory=".phpunit.cache"',
    '         executionOrder="random"',
    '         failOnWarning="true"',
    '         failOnRisky="true"',
    '         failOnDeprecation="true"',
    '         beStrictAboutOutputDuringTests="true"',
    '         colors="true">',
    '    <testsuites>',
    '        <testsuite name="unit"><directory>tests/Unit</directory></testsuite>',
    '        <testsuite name="functional"><directory>tests/Functional</directory></testsuite>',
    '        <testsuite name="behat-bridge"><file>tests/Bridge/BehatTest.php</file></testsuite>',
    '    </testsuites>',
    '    <coverage driver="pcov" pathCoverage="false" ignoreDeprecatedCodeUnits="true">',
    '        <report>',
    '            <clover outputFile="var/coverage/clover.xml"/>',
    '            <html outputDirectory="var/coverage/html"/>',
    '        </report>',
    '    </coverage>',
    '    <source restrictNotices="true" restrictWarnings="true">',
    '        <include>',
    '            <directory>src</directory>',
    '        </include>',
    '        <exclude>',
    '            <directory>src/Migrations</directory>',
    '            <file>src/Kernel.php</file>',
    '        </exclude>',
    '    </source>',
    '    <extensions>',
    '        <bootstrap class="App\\Tests\\Extension\\ResetDatabaseExtension">',
    '            <parameter name="dsn" value="sqlite:///:memory:"/>',
    '        </bootstrap>',
    '    </extensions>',
    '    <php>',
    '        <env name="APP_ENV" value="test"/>',
    '        <env name="KERNEL_CLASS" value="App\\Kernel"/>',
    '        <ini name="display_errors" value="1"/>',
    '        <server name="SHELL_VERBOSITY" value="-1"/>',
    '    </php>',
    '    <logging>',
    '        <junit outputFile="var/test-results/junit.xml"/>',
    '    </logging>',
    '</phpunit>',
  ].join('\n') + '\n';
  put(root, 'phpunit.xml', phpunitXml);
  put(root, 'phpunit.xml.dist', phpunitXml);

  put(root, 'tests/Behat/FeatureContext.php', [
    '<?php',
    'namespace App\\Tests\\Behat;',
    '',
    'use Behat\\Behat\\Context\\Context;',
    'use Behat\\Gherkin\\Node\\TableNode;',
    '',
    'class FeatureContext implements Context',
    '{',
    '    /**',
    '     * @Given I am logged in as :email',
    '     */',
    '    public function iAmLoggedInAs(string $email): void { }',
    '',
    '    /**',
    '     * @Given I have :count items in the cart',
    '     */',
    '    public function iHaveItemsInTheCart(int $count): void { }',
    '',
    '    /**',
    '     * @When I open the cart',
    '     */',
    '    public function iOpenTheCart(): void { }',
    '',
    '    /**',
    '     * @Then I should see :text',
    '     */',
    '    public function iShouldSee(string $text): void { }',
    '',
    '    /**',
    '     * @Given the following products exist:',
    '     */',
    '    public function theFollowingProductsExist(TableNode $table): void { }',
    '',
    '    /**',
    '     * @Then a step nobody calls',
    '     */',
    '    public function unusedStep(): void { }',
    '}',
  ].join('\n') + '\n');
}

function observabilityAndAssets(root: string): void {
  put(root, 'monitoring/grafana/dashboards/symfony.json', JSON.stringify({
    title: 'Symfony',
    uid: 'symfony-overview',
    schemaVersion: 39,
    refresh: '30s',
    time: { from: 'now-6h', to: 'now' },
    templating: { list: [{ name: 'env', type: 'custom', query: 'prod,dev' }] },
    panels: [
      { id: 1, type: 'timeseries', title: 'Requests per second', datasource: { type: 'prometheus', uid: 'prom' }, targets: [{ expr: 'sum(rate(http_requests_total[5m]))' }] },
      { id: 2, type: 'stat', title: 'Error rate', datasource: { type: 'prometheus', uid: 'prom' }, targets: [{ expr: 'sum(rate(http_requests_total{status=~"5.."}[5m]))' }], thresholds: { steps: [{ color: 'green', value: null }, { color: 'red', value: 1 }] } },
      { id: 3, type: 'table', title: 'Slow queries', datasource: { type: 'loki', uid: 'loki' }, targets: [{ expr: '{job="symfony"} |= "Slow query"' }] },
    ],
  }, null, 2) + '\n');

  put(root, 'monitoring/grafana/provisioning/dashboards/acme.yaml', [
    'apiVersion: 1',
    'providers:',
    '    - name: acme',
    '      folder: Acme',
    '      type: file',
    '      options:',
    '          path: /etc/grafana/dashboards',
  ].join('\n') + '\n');

  put(root, 'proto/orders.proto', [
    'syntax = "proto3";',
    '',
    'package acme.orders.v1;',
    '',
    'option php_namespace = "Acme\\\\Orders\\\\V1";',
    'option php_metadata_namespace = "Acme\\\\Orders\\\\V1\\\\Meta";',
    '',
    'service Orders {',
    '    rpc GetOrder (GetOrderRequest) returns (Order) {}',
    '    rpc ListOrders (ListOrdersRequest) returns (stream Order) {}',
    '    rpc PlaceOrder (PlaceOrderRequest) returns (Order) {}',
    '}',
    '',
    'message GetOrderRequest {',
    '    string id = 1;',
    '}',
    '',
    'message ListOrdersRequest {',
    '    int32 page_size = 1;',
    '    string page_token = 2;',
    '}',
    '',
    'message PlaceOrderRequest {',
    '    repeated string skus = 1;',
    '}',
    '',
    'message Order {',
    '    string id = 1;',
    '    double total = 2;',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Grpc/OrdersClient.php', [
    '<?php',
    'namespace App\\Grpc;',
    '',
    'use Acme\\Orders\\V1\\GetOrderRequest;',
    'use Grpc\\ChannelCredentials;',
    '',
    'class OrdersClient',
    '{',
    '    public function fetch(string $id): void',
    '    {',
    '        $client = new \\Acme\\Orders\\V1\\OrdersClient("orders:50051", [',
    '            "credentials" => ChannelCredentials::createInsecure(),',
    '        ]);',
    '        [$response, $status] = $client->GetOrder(new GetOrderRequest(["id" => $id]))->wait();',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Asset/AssetPipeline.php', [
    '<?php',
    'namespace App\\Asset;',
    '',
    'use Symfony\\Component\\AssetMapper\\AssetMapperInterface;',
    '',
    'class AssetPipeline',
    '{',
    '    public function configure($mapper): void',
    '    {',
    '        $mapper->setOutputPath("public/assets");',
    '        $mapper->setPublicPath("/assets");',
    '        $mapper->setExtensions([".js", ".css", ".svg"]);',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'assets/controllers/hello_controller.js', [
    'import { Controller } from "@hotwired/stimulus";',
    '',
    'export default class extends Controller {',
    '    static targets = ["output"];',
    '    static values = { name: String };',
    '',
    '    connect() {',
    '        this.outputTarget.textContent = `Hello ${this.nameValue}`;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'assets/controllers.json', JSON.stringify({
    controllers: {
      '@symfony/ux-turbo': { turbo: { enabled: true, fetch: 'eager' } },
      '@symfony/ux-chartjs': { chart: { enabled: false, fetch: 'lazy' } },
    },
    entrypoints: [],
  }, null, 2) + '\n');
}

function repositories(root: string): void {
  put(root, 'src/Repository/OrderReportRepository.php', [
    '<?php',
    'namespace App\\Repository;',
    '',
    'use Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository;',
    'use Doctrine\\Persistence\\ManagerRegistry;',
    'use App\\Entity\\Order;',
    '',
    'class OrderReportRepository extends ServiceEntityRepository',
    '{',
    '    public function __construct(ManagerRegistry $registry)',
    '    {',
    '        parent::__construct($registry, Order::class);',
    '    }',
    '',
    '    public function complexReport(array $filters): array',
    '    {',
    '        $qb = $this->createQueryBuilder("o")',
    '            ->select("o", "c", "l")',
    '            ->leftJoin("o.customer", "c")',
    '            ->leftJoin("o.lines", "l")',
    '            ->innerJoin("o.channel", "ch")',
    '            ->where("o.placedAt >= :from")',
    '            ->andWhere("o.placedAt <= :to")',
    '            ->andWhere("c.country IN (:countries)")',
    '            ->andWhere("o.total > :minimum")',
    '            ->andWhere("ch.code = :channel")',
    '            ->groupBy("o.id")',
    '            ->having("SUM(l.quantity) > 0")',
    '            ->orderBy("o.placedAt", "DESC")',
    '            ->setMaxResults(100)',
    '            ->setFirstResult($filters["page"] * 100);',
    '',
    '        return $qb->getQuery()->getResult();',
    '    }',
    '',
    '    public function raw(): array',
    '    {',
    '        $sql = "SELECT * FROM orders WHERE customer_id = " . $_GET["customer"];',
    '',
    '        return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAllAssociative();',
    '    }',
    '',
    '    public function everything(): array',
    '    {',
    '        return $this->findAll();',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Service/ErrorProne.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class ErrorProne',
    '{',
    '    public function run(string $path): void',
    '    {',
    '        try {',
    '            $handle = @fopen($path, "r");',
    '            if ($handle === false) {',
    '                throw new \\RuntimeException("cannot open");',
    '            }',
    '        } catch (\\Throwable $e) {',
    '        }',
    '',
    '        try {',
    '            $this->inner();',
    '        } catch (\\Exception $e) {',
    '            error_log($e->getMessage());',
    '        } finally {',
    '            $this->cleanup();',
    '        }',
    '',
    '        set_error_handler(static function (int $no, string $str): bool { return true; });',
    '        set_exception_handler(static function (\\Throwable $e): void { });',
    '        register_shutdown_function(static function (): void { });',
    '    }',
    '',
    '    private function inner(): void { }',
    '    private function cleanup(): void { }',
    '}',
  ].join('\n') + '\n');
}

/** Everything in this file. */
export function addBatchNine(root: string): void {
  apiAndTests(root);
  observabilityAndAssets(root);
  repositories(root);
}
