// SPDX-FileCopyrightText: 2026 Ángel Guzmán Maeso <angel@guzmanmaeso.com>
// SPDX-License-Identifier: MIT
/**
 * PHP written in the shapes the remaining analysers look for.
 *
 * These modules read source rather than configuration, and the fixtures had
 * none of what they search for: Gedmo tree and slug mappings, PHPUnit
 * exception expectations and custom assertions, repeated password fields,
 * serializer context builders, chained cache adapters, Sonata admin classes.
 * Each block was written from the literals the module itself searches for.
 */

import * as fs from 'fs';
import * as path from 'path';

function put(root: string, rel: string, content: string): void {
  const full = path.join(root, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

/** Gedmo tree and sluggable, in both attribute and annotation form. */
function gedmoTreeAndSlug(root: string): void {
  put(root, 'src/Entity/Category.php', [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    'use Gedmo\\Mapping\\Annotation as Gedmo;',
    '',
    '/**',
    ' * @Gedmo\\Tree(type="nested")',
    ' * @ORM\\Entity(repositoryClass="App\\Repository\\CategoryRepository")',
    ' */',
    '#[Gedmo\\Tree(type: "nested")]',
    '#[ORM\\Entity]',
    'class Category',
    '{',
    '    /**',
    '     * @Gedmo\\TreeLeft',
    '     * @ORM\\Column(type="integer")',
    '     */',
    '    #[Gedmo\\TreeLeft]',
    '    private $lft;',
    '',
    '    /**',
    '     * @Gedmo\\TreeRight',
    '     */',
    '    #[Gedmo\\TreeRight]',
    '    private $rgt;',
    '',
    '    /**',
    '     * @Gedmo\\TreeLevel',
    '     */',
    '    #[Gedmo\\TreeLevel]',
    '    private $lvl;',
    '',
    '    /**',
    '     * @Gedmo\\TreeRoot',
    '     */',
    '    #[Gedmo\\TreeRoot]',
    '    private $root;',
    '',
    '    /**',
    '     * @Gedmo\\TreeParent',
    '     * @ORM\\ManyToOne(targetEntity="Category", inversedBy="children")',
    '     */',
    '    #[Gedmo\\TreeParent]',
    '    private $parent;',
    '',
    '    /**',
    '     * @Gedmo\\Slug(fields={"title"}, unique=true)',
    '     * @ORM\\Column(length=128, unique=true)',
    '     */',
    '    #[Gedmo\\Slug(fields: ["title"], unique: true)]',
    '    private $slug;',
    '',
    '    /**',
    '     * @Gedmo\\Slug(fields={"title"}, handlers={',
    '     *     @Gedmo\\SlugHandler(class="Gedmo\\Sluggable\\Handler\\TreeSlugHandler")',
    '     * })',
    '     */',
    '    private $path;',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Entity/Article.php', [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Gedmo\\Mapping\\Annotation as Gedmo;',
    'use Doctrine\\ORM\\Mapping as ORM;',
    '',
    '#[ORM\\Entity]',
    'class Article',
    '{',
    '    /**',
    '     * @Gedmo\\Slug(fields={"title"}, handlers={',
    '     *     @Gedmo\\SlugHandler(class="Gedmo\\Sluggable\\Handler\\RelativeSlugHandler", options={',
    '     *         @Gedmo\\SlugHandlerOption(name="relationField", value="category")',
    '     *     })',
    '     * })',
    '     * @ORM\\Column(length=128)',
    '     */',
    '    private $slug;',
    '',
    '    #[ORM\\Column(length: 255)]',
    '    private $title;',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/stof_doctrine_extensions.yaml', [
    'stof_doctrine_extensions:',
    '    default_locale: en',
    '    orm:',
    '        default:',
    '            tree: true',
    '            sluggable: true',
    '            timestampable: true',
    '            blameable: true',
    '            loggable: true',
  ].join('\n') + '\n');
}

/** PHPUnit: exception expectations, custom assertions, the old annotations. */
function phpunitPatterns(root: string): void {
  put(root, 'tests/Unit/ExceptionTest.php', [
    '<?php',
    'namespace App\\Tests\\Unit;',
    '',
    'use PHPUnit\\Framework\\TestCase;',
    'use PHPUnit\\Framework\\Assert;',
    '',
    'class ExceptionTest extends TestCase',
    '{',
    '    public function testModernExpectation(): void',
    '    {',
    '        $this->expectException(\\InvalidArgumentException::class);',
    '        $this->expectExceptionMessage("bad input");',
    '        $this->expectExceptionCode(400);',
    '        throw new \\InvalidArgumentException("bad input", 400);',
    '    }',
    '',
    '    /**',
    '     * @expectedException \\RuntimeException',
    '     * @expectedExceptionMessage boom',
    '     */',
    '    public function testLegacyAnnotation(): void',
    '    {',
    '        throw new \\RuntimeException("boom");',
    '    }',
    '',
    '    public function testTryCatchInsteadOfExpectation(): void',
    '    {',
    '        try {',
    '            throw new \\LogicException("x");',
    '            $this->fail("should not reach here");',
    '        } catch (\\LogicException $e) {',
    '            $this->assertSame("x", $e->getMessage());',
    '            Assert::assertEquals("x", $e->getMessage());',
    '        }',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'tests/Support/CustomAssertions.php', [
    '<?php',
    'namespace App\\Tests\\Support;',
    '',
    'use PHPUnit\\Framework\\Assert;',
    'use PHPUnit\\Framework\\Constraint\\Constraint;',
    '',
    '/**',
    ' * Assertions shared across the suite.',
    ' */',
    'trait CustomAssertions',
    '{',
    '    public function assertIsMoney($value, string $message = ""): void',
    '    {',
    '        $this->assertMatchesRegularExpression("/^\\\\d+\\\\.\\\\d{2}$/", (string) $value, $message);',
    '    }',
    '',
    '    public function assertThatOrderIsPaid($order): void',
    '    {',
    '        $this->assertThat($order->status, new IsPaidConstraint());',
    '    }',
    '',
    '    public function assertNever(): void',
    '    {',
    '        Assert::fail("this should not happen");',
    '    }',
    '}',
    '',
    'class IsPaidConstraint extends Constraint',
    '{',
    '    public function toString(): string { return "is paid"; }',
    '    protected function matches($other): bool { return $other === "paid"; }',
    '}',
  ].join('\n') + '\n');
}

/** Repeated password fields, and the comparison that should be constant time. */
function repeatedFields(root: string): void {
  put(root, 'src/Form/RegistrationType.php', [
    '<?php',
    'namespace App\\Form;',
    '',
    'use Symfony\\Component\\Form\\AbstractType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType;',
    'use Symfony\\Component\\Form\\FormBuilderInterface;',
    '',
    'class RegistrationType extends AbstractType',
    '{',
    '    public function buildForm(FormBuilderInterface $builder, array $options): void',
    '    {',
    '        $builder->add("plainPassword", RepeatedType::class, [',
    '            "type" => PasswordType::class,',
    '            "invalid_message" => "The password fields must match.",',
    '            "first_options" => ["label" => "Password"],',
    '            "second_options" => ["label" => "Confirm password"],',
    '            "mapped" => false,',
    '        ]);',
    '',
    '        $builder->add("email", RepeatedType::class, [',
    '            "first_options" => ["label" => "Email"],',
    '            "second_options" => ["label" => "Confirm email"],',
    '        ]);',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Service/TokenComparer.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class TokenComparer',
    '{',
    '    public function unsafe(string $a, string $b): bool',
    '    {',
    '        // Timing-sensitive comparison written with ===',
    '        return $a === $b;',
    '    }',
    '',
    '    public function safe(string $a, string $b): bool',
    '    {',
    '        return hash_equals($a, $b);',
    '    }',
    '}',
  ].join('\n') + '\n');
}

/** Serializer context builders, chained caches, Sonata admin. */
function serializerCacheAdmin(root: string): void {
  put(root, 'src/Serializer/OrderContextBuilder.php', [
    '<?php',
    'namespace App\\Serializer;',
    '',
    'use ApiPlatform\\Serializer\\SerializerContextBuilderInterface;',
    'use Symfony\\Component\\HttpFoundation\\Request;',
    '',
    'class OrderContextBuilder implements SerializerContextBuilderInterface',
    '{',
    '    public function __construct(private SerializerContextBuilderInterface $decorated) {}',
    '',
    '    public function createFromRequest(Request $request, bool $normalization, ?array $extractedAttributes = null): array',
    '    {',
    '        $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);',
    '        $context["groups"][] = "order:admin";',
    '        return $context;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Serializer/ContextFactory.php', [
    '<?php',
    'namespace App\\Serializer;',
    '',
    'use Symfony\\Component\\Serializer\\Context\\Normalizer\\DateTimeNormalizerContextBuilder;',
    'use Symfony\\Component\\Serializer\\Context\\Normalizer\\ObjectNormalizerContextBuilder;',
    '',
    'class ContextFactory',
    '{',
    '    public function build(): array',
    '    {',
    '        $context = (new ObjectNormalizerContextBuilder())',
    '            ->withGroups(["order:read"])',
    '            ->withSkipNullValues(true)',
    '            ->toArray();',
    '',
    '        return (new DateTimeNormalizerContextBuilder())',
    '            ->withContext($context)',
    '            ->withFormat("Y-m-d")',
    '            ->toArray();',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Cache/ChainedCache.php', [
    '<?php',
    'namespace App\\Cache;',
    '',
    'use Symfony\\Component\\Cache\\Adapter\\ArrayAdapter;',
    'use Symfony\\Component\\Cache\\Adapter\\ChainAdapter;',
    'use Symfony\\Component\\Cache\\Adapter\\RedisAdapter;',
    'use Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter;',
    '',
    'class ChainedCache',
    '{',
    '    public function build(): ChainAdapter',
    '    {',
    '        $chain = new ChainAdapter([new ArrayAdapter(), new RedisAdapter($this->redis)], 30);',
    '        $tagAware = new TagAwareAdapter($chain);',
    '        $tagAware->invalidateTags(["orders"]);',
    '        return $chain;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/cache_chain.yaml', [
    'framework:',
    '    cache:',
    '        pools:',
    '            app.cache.chained:',
    '                adapters: [cache.adapter.array, cache.adapter.redis]',
    '                tags: true',
    '            app.cache.tagged:',
    '                adapter: cache.app',
    '                tags: app.cache.tag_store',
  ].join('\n') + '\n');

  put(root, 'src/Admin/OrderAdmin.php', [
    '<?php',
    'namespace App\\Admin;',
    '',
    'use Sonata\\AdminBundle\\Admin\\AbstractAdmin;',
    'use Sonata\\AdminBundle\\Datagrid\\DatagridMapper;',
    'use Sonata\\AdminBundle\\Datagrid\\ListMapper;',
    'use Sonata\\AdminBundle\\Form\\FormMapper;',
    '',
    'class OrderAdmin extends AbstractAdmin',
    '{',
    '    protected function configureDatagridFilters(DatagridMapper $filter): void',
    '    {',
    '        $filter->add("reference")->add("status");',
    '    }',
    '',
    '    protected function configureListFields(ListMapper $list): void',
    '    {',
    '        $list->addIdentifier("reference")->add("status")->add("total");',
    '    }',
    '',
    '    protected function configureFormFields(FormMapper $form): void',
    '    {',
    '        $form->add("reference")->add("status");',
    '    }',
    '',
    '    protected function configureBatchActions(array $actions): array',
    '    {',
    '        $actions["export"] = ["ask_confirmation" => true];',
    '        return $actions;',
    '    }',
    '',
    '    protected function configureExportFields(): array { return ["reference", "total"]; }',
    '    protected function configureDefaultSortValues(array &$sortValues): void',
    '    {',
    '        $sortValues["_sort_by"] = "createdAt";',
    '    }',
    '}',
  ].join('\n') + '\n');
}

/** Null-coalescing and the older shapes it replaces. */
function nullCoalescing(root: string): void {
  put(root, 'src/Service/Defaults.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class Defaults',
    '{',
    '    public function modern(array $options): array',
    '    {',
    '        $timeout = $options["timeout"] ?? 30;',
    '        $retries = $options["retries"] ?? null;',
    '        $options["locale"] ??= "en";',
    '        $name = $this->config?->getName() ?? "unnamed";',
    '        return [$timeout, $retries, $name, $options];',
    '    }',
    '',
    '    public function legacy(array $options): array',
    '    {',
    '        // The shapes ?? replaces, still common in older code',
    '        $timeout = isset($options["timeout"]) ? $options["timeout"] : 30;',
    '        $retries = array_key_exists("retries", $options) ? $options["retries"] : null;',
    '        $locale = empty($options["locale"]) ? "en" : $options["locale"];',
    '        $name = isset($this->config) && $this->config->getName() ? $this->config->getName() : "unnamed";',
    '        return [$timeout, $retries, $locale, $name];',
    '    }',
    '}',
  ].join('\n') + '\n');
}

/** nelmio/security-bundle and pgbouncer. */
function securityBundleAndPgbouncer(root: string): void {
  put(root, 'config/packages/nelmio_security.yaml', [
    'nelmio_security:',
    '    signed_cookie:',
    '        names: ["*"]',
    '    clickjacking:',
    '        paths:',
    '            "^/.*": DENY',
    '    content_type:',
    '        nosniff: true',
    '    xss_protection:',
    '        enabled: true',
    '        mode_block: true',
    '    forced_ssl:',
    '        enabled: false',
    '        hsts_max_age: 31536000',
    '        hsts_subdomains: true',
    '    csp:',
    '        enabled: true',
    '        report_logger_service: logger',
    '        enforce:',
    '            default-src: ["\'self\'"]',
    '            script-src: ["\'self\'", "\'unsafe-inline\'"]',
    '            img-src: ["\'self\'", "data:"]',
  ].join('\n') + '\n');

  put(root, 'docker/pgbouncer/pgbouncer.ini', [
    '[databases]',
    'app = host=postgres port=5432 dbname=app',
    '',
    '[pgbouncer]',
    'listen_addr = 0.0.0.0',
    'listen_port = 6432',
    'auth_type = scram-sha-256',
    'pool_mode = transaction',
    'max_client_conn = 200',
    'default_pool_size = 20',
    'server_reset_query = DISCARD ALL',
  ].join('\n') + '\n');

  put(root, '.env.pgbouncer', 'DATABASE_URL="postgresql://app@pgbouncer:6432/app?serverVersion=16"\n');
}

/** Everything in this file. */
export function addPhpPatterns(root: string): void {
  messengerConsumers(root);
  assortedPhpAndConfig(root);
  toolingConfigs(root);
  gedmoTreeAndSlug(root);
  phpunitPatterns(root);
  repeatedFields(root);
  serializerCacheAdmin(root);
  nullCoalescing(root);
  securityBundleAndPgbouncer(root);
}

/** Messenger consumption in orchestration, at the paths the analyser reads. */
function messengerConsumers(root: string): void {
  put(root, 'Makefile', [
    '.PHONY: consume consume-high consume-failed test',
    '',
    'consume:',
    '\tphp bin/console messenger:consume async --limit=10 --time-limit=3600 --memory-limit=128M',
    '',
    'consume-high:',
    '\tphp bin/console messenger:consume async_priority_high -l 100 --time-limit=900',
    '',
    'consume-failed:',
    '\tphp bin/console messenger:consume failed --limit=1',
    '',
    'consume-all:',
    '\tphp bin/console messenger:consume async async_priority_high --limit=50',
    '',
    'test:',
    '\tvendor/bin/phpunit',
  ].join('\n') + '\n');

  put(root, 'docker/supervisor/messenger.conf', [
    '[program:messenger-async]',
    'command=php /var/www/bin/console messenger:consume async --limit=10 --time-limit=3600',
    'numprocs=4',
    'process_name=%(program_name)s_%(process_num)02d',
    'autostart=true',
    'autorestart=true',
    'user=www-data',
    '',
    '[program:messenger-high]',
    'command=php /var/www/bin/console messenger:consume async_priority_high -l 100',
    'numprocs=2',
    'autorestart=unexpected',
  ].join('\n') + '\n');

  put(root, 'k8s/worker-deployment.yaml', [
    'apiVersion: apps/v1',
    'kind: Deployment',
    'metadata:',
    '    name: messenger-worker',
    'spec:',
    '    replicas: 3',
    '    template:',
    '        spec:',
    '            containers:',
    '                - name: worker',
    '                  image: acme/app:latest',
    '                  command: ["php", "bin/console", "messenger:consume", "async", "--limit=50"]',
  ].join('\n') + '\n');
}

/** ICU message format, Mercure, heredoc, kernel events, Doctrine lifecycle. */
function assortedPhpAndConfig(root: string): void {
  put(root, 'translations/messages+intl-icu.en.yaml', [
    'order.count: >-',
    '    {count, plural,',
    '        =0 {No orders}',
    '        =1 {One order}',
    '        other {# orders}',
    '    }',
    'order.status: >-',
    '    {status, select,',
    '        paid {Paid}',
    '        pending {Pending}',
    '        other {Unknown}',
    '    }',
    'order.position: >-',
    '    {pos, selectordinal,',
    '        one {#st}',
    '        two {#nd}',
    '        other {#th}',
    '    }',
    'order.due: "{date, date, long} at {date, time, short}"',
  ].join('\n') + '\n');

  put(root, 'config/packages/mercure.yaml', [
    'mercure:',
    '    hubs:',
    '        default:',
    '            url: "%env(MERCURE_URL)%"',
    '            public_url: "%env(MERCURE_PUBLIC_URL)%"',
    '            jwt:',
    '                secret: "%env(MERCURE_JWT_SECRET)%"',
    '                publish: ["*"]',
  ].join('\n') + '\n');

  put(root, 'src/Service/Publisher.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'use Symfony\\Component\\Mercure\\HubInterface;',
    'use Symfony\\Component\\Mercure\\Update;',
    '',
    'class Publisher',
    '{',
    '    public function __construct(private HubInterface $hub) {}',
    '',
    '    public function publish(array $data): void',
    '    {',
    '        $this->hub->publish(new Update("https://example.com/orders", json_encode($data)));',
    '        // Private update: only subscribers with a matching JWT receive it',
    '        $this->hub->publish(new Update("https://example.com/orders/1", "{}", private: true));',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Service/Queries.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class Queries',
    '{',
    '    public function heredoc(string $status): string',
    '    {',
    '        // Interpolating into a heredoc holding SQL',
    '        return <<<SQL',
    '            SELECT * FROM orders WHERE status = \'$status\'',
    '        SQL;',
    '    }',
    '',
    '    public function nowdoc(): string',
    '    {',
    '        return <<<\'SQL\'',
    '            SELECT * FROM orders WHERE status = :status',
    '        SQL;',
    '    }',
    '',
    '    public function html(string $name): string',
    '    {',
    '        // Unescaped interpolation into markup',
    '        return <<<HTML',
    '            <div class="user">$name</div>',
    '        HTML;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/EventSubscriber/KernelSubscriber.php', [
    '<?php',
    'namespace App\\EventSubscriber;',
    '',
    'use Symfony\\Component\\EventDispatcher\\EventSubscriberInterface;',
    'use Symfony\\Component\\HttpKernel\\Event\\RequestEvent;',
    'use Symfony\\Component\\HttpKernel\\Event\\ResponseEvent;',
    'use Symfony\\Component\\HttpKernel\\KernelEvents;',
    '',
    'class KernelSubscriber implements EventSubscriberInterface',
    '{',
    '    public static function getSubscribedEvents(): array',
    '    {',
    '        return [',
    '            KernelEvents::REQUEST => [["onRequest", 250]],',
    '            KernelEvents::RESPONSE => "onResponse",',
    '            KernelEvents::EXCEPTION => [["onException", -64]],',
    '            KernelEvents::TERMINATE => "onTerminate",',
    '        ];',
    '    }',
    '',
    '    public function onRequest(RequestEvent $event): void',
    '    {',
    '        if (!$event->isMainRequest()) { return; }',
    '    }',
    '',
    '    public function onResponse(ResponseEvent $event): void {}',
    '    public function onException($event): void {}',
    '    public function onTerminate($event): void {}',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/EventListener/OrderLifecycleListener.php', [
    '<?php',
    'namespace App\\EventListener;',
    '',
    'use Doctrine\\Bundle\\DoctrineBundle\\Attribute\\AsDoctrineListener;',
    'use Doctrine\\Bundle\\DoctrineBundle\\Attribute\\AsEntityListener;',
    'use Doctrine\\ORM\\Event\\PostPersistEventArgs;',
    'use Doctrine\\ORM\\Events;',
    '',
    '#[AsDoctrineListener(event: Events::postFlush)]',
    'class OrderLifecycleListener',
    '{',
    '    public function postFlush($args): void',
    '    {',
    '        // Flushing from inside a flush listener re-enters the unit of work',
    '        $args->getObjectManager()->flush();',
    '    }',
    '}',
    '',
    '#[AsEntityListener(event: Events::postPersist, entity: \\App\\Entity\\Order::class)]',
    'class OrderPersistListener',
    '{',
    '    public function postPersist($order, PostPersistEventArgs $args): void {}',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Entity/LifecycleOrder.php', [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    '',
    '/**',
    ' * @ORM\\Entity',
    ' * @ORM\\HasLifecycleCallbacks',
    ' */',
    '#[ORM\\Entity]',
    '#[ORM\\HasLifecycleCallbacks]',
    'class LifecycleOrder',
    '{',
    '    #[ORM\\PrePersist]',
    '    public function onPrePersist(): void {}',
    '',
    '    #[ORM\\PreUpdate]',
    '    public function onPreUpdate(): void {}',
    '',
    '    #[ORM\\PostLoad]',
    '    public function onPostLoad(): void {}',
    '}',
  ].join('\n') + '\n');
}

/** Rector, Varnish, FrankenPHP, JWT. */
function toolingConfigs(root: string): void {
  put(root, 'rector.php', [
    '<?php',
    '',
    'declare(strict_types=1);',
    '',
    'use Rector\\Config\\RectorConfig;',
    'use Rector\\Set\\ValueObject\\LevelSetList;',
    'use Rector\\Set\\ValueObject\\SetList;',
    'use Rector\\Symfony\\Set\\SymfonySetList;',
    'use Rector\\DeadCode\\Rector\\ClassMethod\\RemoveUnusedPrivateMethodRector;',
    '',
    'return RectorConfig::configure()',
    '    ->withPaths([__DIR__ . "/src", __DIR__ . "/tests"])',
    '    ->withParallel()',
    '    ->withCache(__DIR__ . "/var/rector")',
    '    ->withSets([',
    '        LevelSetList::UP_TO_PHP_83,',
    '        SetList::DEAD_CODE,',
    '        SetList::CODE_QUALITY,',
    '        SetList::TYPE_DECLARATION,',
    '        SymfonySetList::SYMFONY_64,',
    '    ])',
    '    ->withRules([RemoveUnusedPrivateMethodRector::class])',
    '    ->withSkip([__DIR__ . "/src/Migrations"]);',
  ].join('\n') + '\n');

  put(root, 'docker/varnish/default.vcl', [
    'vcl 4.1;',
    '',
    'backend default {',
    '    .host = "nginx";',
    '    .port = "80";',
    '    .probe = {',
    '        .url = "/health";',
    '        .interval = 5s;',
    '        .timeout = 2s;',
    '    }',
    '}',
    '',
    'acl purgers {',
    '    "localhost";',
    '    "10.0.0.0"/8;',
    '}',
    '',
    'sub vcl_recv {',
    '    if (req.method == "PURGE") {',
    '        if (!client.ip ~ purgers) { return (synth(405)); }',
    '        return (purge);',
    '    }',
    '    if (req.method == "BAN") {',
    '        ban("obj.http.x-url ~ " + req.http.x-ban);',
    '        return (synth(200));',
    '    }',
    '    set req.http.X-Forwarded-For = client.ip;',
    '    unset req.http.Cookie;',
    '}',
  ].join('\n') + '\n');

  put(root, 'Caddyfile', [
    '{',
    '    frankenphp',
    '    order php_server before file_server',
    '}',
    '',
    'app.example.com {',
    '    root * /app/public',
    '    encode zstd gzip',
    '    php_server',
    '    header {',
    '        X-Frame-Options DENY',
    '        X-Content-Type-Options nosniff',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/lexik_jwt_authentication.yaml', [
    'lexik_jwt_authentication:',
    '    secret_key: "%env(resolve:JWT_SECRET_KEY)%"',
    '    public_key: "%env(resolve:JWT_PUBLIC_KEY)%"',
    '    pass_phrase: "%env(JWT_PASSPHRASE)%"',
    '    token_ttl: 3600',
    '    token_extractors:',
    '        authorization_header:',
    '            enabled: true',
    '            prefix: Bearer',
    '            name: Authorization',
    '        cookie:',
    '            enabled: false',
    '    set_cookies:',
    '        BEARER:',
    '            lifetime: 3600',
    '            samesite: strict',
    '            secure: true',
    '            httpOnly: true',
  ].join('\n') + '\n');
}
