// SPDX-FileCopyrightText: 2026 Ángel Guzmán Maeso <angel@guzmanmaeso.com>
// SPDX-License-Identifier: MIT
/**
 * PHP written in the shapes the remaining analysers look for.
 *
 * These modules read source rather than configuration, and the fixtures had
 * none of what they search for: Gedmo tree and slug mappings, PHPUnit
 * exception expectations and custom assertions, repeated password fields,
 * serializer context builders, chained cache adapters, Sonata admin classes.
 * Each block was written from the literals the module itself searches for.
 */

import * as fs from 'fs';
import * as path from 'path';

function put(root: string, rel: string, content: string): void {
  const full = path.join(root, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

/** Gedmo tree and sluggable, in both attribute and annotation form. */
function gedmoTreeAndSlug(root: string): void {
  put(root, 'src/Entity/Category.php', [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    'use Gedmo\\Mapping\\Annotation as Gedmo;',
    '',
    '/**',
    ' * @Gedmo\\Tree(type="nested")',
    ' * @ORM\\Entity(repositoryClass="App\\Repository\\CategoryRepository")',
    ' */',
    '#[Gedmo\\Tree(type: "nested")]',
    '#[ORM\\Entity]',
    'class Category',
    '{',
    '    /**',
    '     * @Gedmo\\TreeLeft',
    '     * @ORM\\Column(type="integer")',
    '     */',
    '    #[Gedmo\\TreeLeft]',
    '    private $lft;',
    '',
    '    /**',
    '     * @Gedmo\\TreeRight',
    '     */',
    '    #[Gedmo\\TreeRight]',
    '    private $rgt;',
    '',
    '    /**',
    '     * @Gedmo\\TreeLevel',
    '     */',
    '    #[Gedmo\\TreeLevel]',
    '    private $lvl;',
    '',
    '    /**',
    '     * @Gedmo\\TreeRoot',
    '     */',
    '    #[Gedmo\\TreeRoot]',
    '    private $root;',
    '',
    '    /**',
    '     * @Gedmo\\TreeParent',
    '     * @ORM\\ManyToOne(targetEntity="Category", inversedBy="children")',
    '     */',
    '    #[Gedmo\\TreeParent]',
    '    private $parent;',
    '',
    '    /**',
    '     * @Gedmo\\Slug(fields={"title"}, unique=true)',
    '     * @ORM\\Column(length=128, unique=true)',
    '     */',
    '    #[Gedmo\\Slug(fields: ["title"], unique: true)]',
    '    private $slug;',
    '',
    '    /**',
    '     * @Gedmo\\Slug(fields={"title"}, handlers={',
    '     *     @Gedmo\\SlugHandler(class="Gedmo\\Sluggable\\Handler\\TreeSlugHandler")',
    '     * })',
    '     */',
    '    private $path;',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Entity/Article.php', [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Gedmo\\Mapping\\Annotation as Gedmo;',
    'use Doctrine\\ORM\\Mapping as ORM;',
    '',
    '#[ORM\\Entity]',
    'class Article',
    '{',
    '    /**',
    '     * @Gedmo\\Slug(fields={"title"}, handlers={',
    '     *     @Gedmo\\SlugHandler(class="Gedmo\\Sluggable\\Handler\\RelativeSlugHandler", options={',
    '     *         @Gedmo\\SlugHandlerOption(name="relationField", value="category")',
    '     *     })',
    '     * })',
    '     * @ORM\\Column(length=128)',
    '     */',
    '    private $slug;',
    '',
    '    #[ORM\\Column(length: 255)]',
    '    private $title;',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/stof_doctrine_extensions.yaml', [
    'stof_doctrine_extensions:',
    '    default_locale: en',
    '    orm:',
    '        default:',
    '            tree: true',
    '            sluggable: true',
    '            timestampable: true',
    '            blameable: true',
    '            loggable: true',
  ].join('\n') + '\n');
}

/** PHPUnit: exception expectations, custom assertions, the old annotations. */
function phpunitPatterns(root: string): void {
  put(root, 'tests/Unit/ExceptionTest.php', [
    '<?php',
    'namespace App\\Tests\\Unit;',
    '',
    'use PHPUnit\\Framework\\TestCase;',
    'use PHPUnit\\Framework\\Assert;',
    '',
    'class ExceptionTest extends TestCase',
    '{',
    '    public function testModernExpectation(): void',
    '    {',
    '        $this->expectException(\\InvalidArgumentException::class);',
    '        $this->expectExceptionMessage("bad input");',
    '        $this->expectExceptionCode(400);',
    '        throw new \\InvalidArgumentException("bad input", 400);',
    '    }',
    '',
    '    /**',
    '     * @expectedException \\RuntimeException',
    '     * @expectedExceptionMessage boom',
    '     */',
    '    public function testLegacyAnnotation(): void',
    '    {',
    '        throw new \\RuntimeException("boom");',
    '    }',
    '',
    '    public function testTryCatchInsteadOfExpectation(): void',
    '    {',
    '        try {',
    '            throw new \\LogicException("x");',
    '            $this->fail("should not reach here");',
    '        } catch (\\LogicException $e) {',
    '            $this->assertSame("x", $e->getMessage());',
    '            Assert::assertEquals("x", $e->getMessage());',
    '        }',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'tests/Support/CustomAssertions.php', [
    '<?php',
    'namespace App\\Tests\\Support;',
    '',
    'use PHPUnit\\Framework\\Assert;',
    'use PHPUnit\\Framework\\Constraint\\Constraint;',
    '',
    '/**',
    ' * Assertions shared across the suite.',
    ' */',
    'trait CustomAssertions',
    '{',
    '    public function assertIsMoney($value, string $message = ""): void',
    '    {',
    '        $this->assertMatchesRegularExpression("/^\\\\d+\\\\.\\\\d{2}$/", (string) $value, $message);',
    '    }',
    '',
    '    public function assertThatOrderIsPaid($order): void',
    '    {',
    '        $this->assertThat($order->status, new IsPaidConstraint());',
    '    }',
    '',
    '    public function assertNever(): void',
    '    {',
    '        Assert::fail("this should not happen");',
    '    }',
    '}',
    '',
    'class IsPaidConstraint extends Constraint',
    '{',
    '    public function toString(): string { return "is paid"; }',
    '    protected function matches($other): bool { return $other === "paid"; }',
    '}',
  ].join('\n') + '\n');
}

/** Repeated password fields, and the comparison that should be constant time. */
function repeatedFields(root: string): void {
  put(root, 'src/Form/RegistrationType.php', [
    '<?php',
    'namespace App\\Form;',
    '',
    'use Symfony\\Component\\Form\\AbstractType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType;',
    'use Symfony\\Component\\Form\\FormBuilderInterface;',
    '',
    'class RegistrationType extends AbstractType',
    '{',
    '    public function buildForm(FormBuilderInterface $builder, array $options): void',
    '    {',
    '        $builder->add("plainPassword", RepeatedType::class, [',
    '            "type" => PasswordType::class,',
    '            "invalid_message" => "The password fields must match.",',
    '            "first_options" => ["label" => "Password"],',
    '            "second_options" => ["label" => "Confirm password"],',
    '            "mapped" => false,',
    '        ]);',
    '',
    '        $builder->add("email", RepeatedType::class, [',
    '            "first_options" => ["label" => "Email"],',
    '            "second_options" => ["label" => "Confirm email"],',
    '        ]);',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Service/TokenComparer.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class TokenComparer',
    '{',
    '    public function unsafe(string $a, string $b): bool',
    '    {',
    '        // Timing-sensitive comparison written with ===',
    '        return $a === $b;',
    '    }',
    '',
    '    public function safe(string $a, string $b): bool',
    '    {',
    '        return hash_equals($a, $b);',
    '    }',
    '}',
  ].join('\n') + '\n');
}

/** Serializer context builders, chained caches, Sonata admin. */
function serializerCacheAdmin(root: string): void {
  put(root, 'src/Serializer/OrderContextBuilder.php', [
    '<?php',
    'namespace App\\Serializer;',
    '',
    'use ApiPlatform\\Serializer\\SerializerContextBuilderInterface;',
    'use Symfony\\Component\\HttpFoundation\\Request;',
    '',
    'class OrderContextBuilder implements SerializerContextBuilderInterface',
    '{',
    '    public function __construct(private SerializerContextBuilderInterface $decorated) {}',
    '',
    '    public function createFromRequest(Request $request, bool $normalization, ?array $extractedAttributes = null): array',
    '    {',
    '        $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);',
    '        $context["groups"][] = "order:admin";',
    '        return $context;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Serializer/ContextFactory.php', [
    '<?php',
    'namespace App\\Serializer;',
    '',
    'use Symfony\\Component\\Serializer\\Context\\Normalizer\\DateTimeNormalizerContextBuilder;',
    'use Symfony\\Component\\Serializer\\Context\\Normalizer\\ObjectNormalizerContextBuilder;',
    '',
    'class ContextFactory',
    '{',
    '    public function build(): array',
    '    {',
    '        $context = (new ObjectNormalizerContextBuilder())',
    '            ->withGroups(["order:read"])',
    '            ->withSkipNullValues(true)',
    '            ->toArray();',
    '',
    '        return (new DateTimeNormalizerContextBuilder())',
    '            ->withContext($context)',
    '            ->withFormat("Y-m-d")',
    '            ->toArray();',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Cache/ChainedCache.php', [
    '<?php',
    'namespace App\\Cache;',
    '',
    'use Symfony\\Component\\Cache\\Adapter\\ArrayAdapter;',
    'use Symfony\\Component\\Cache\\Adapter\\ChainAdapter;',
    'use Symfony\\Component\\Cache\\Adapter\\RedisAdapter;',
    'use Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter;',
    '',
    'class ChainedCache',
    '{',
    '    public function build(): ChainAdapter',
    '    {',
    '        $chain = new ChainAdapter([new ArrayAdapter(), new RedisAdapter($this->redis)], 30);',
    '        $tagAware = new TagAwareAdapter($chain);',
    '        $tagAware->invalidateTags(["orders"]);',
    '        return $chain;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/cache_chain.yaml', [
    'framework:',
    '    cache:',
    '        pools:',
    '            app.cache.chained:',
    '                adapters: [cache.adapter.array, cache.adapter.redis]',
    '                tags: true',
    '            app.cache.tagged:',
    '                adapter: cache.app',
    '                tags: app.cache.tag_store',
  ].join('\n') + '\n');

  put(root, 'src/Admin/OrderAdmin.php', [
    '<?php',
    'namespace App\\Admin;',
    '',
    'use Sonata\\AdminBundle\\Admin\\AbstractAdmin;',
    'use Sonata\\AdminBundle\\Datagrid\\DatagridMapper;',
    'use Sonata\\AdminBundle\\Datagrid\\ListMapper;',
    'use Sonata\\AdminBundle\\Form\\FormMapper;',
    '',
    'class OrderAdmin extends AbstractAdmin',
    '{',
    '    protected function configureDatagridFilters(DatagridMapper $filter): void',
    '    {',
    '        $filter->add("reference")->add("status");',
    '    }',
    '',
    '    protected function configureListFields(ListMapper $list): void',
    '    {',
    '        $list->addIdentifier("reference")->add("status")->add("total");',
    '    }',
    '',
    '    protected function configureFormFields(FormMapper $form): void',
    '    {',
    '        $form->add("reference")->add("status");',
    '    }',
    '',
    '    protected function configureBatchActions(array $actions): array',
    '    {',
    '        $actions["export"] = ["ask_confirmation" => true];',
    '        return $actions;',
    '    }',
    '',
    '    protected function configureExportFields(): array { return ["reference", "total"]; }',
    '    protected function configureDefaultSortValues(array &$sortValues): void',
    '    {',
    '        $sortValues["_sort_by"] = "createdAt";',
    '    }',
    '}',
  ].join('\n') + '\n');
}

/** Null-coalescing and the older shapes it replaces. */
function nullCoalescing(root: string): void {
  put(root, 'src/Service/Defaults.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class Defaults',
    '{',
    '    public function modern(array $options): array',
    '    {',
    '        $timeout = $options["timeout"] ?? 30;',
    '        $retries = $options["retries"] ?? null;',
    '        $options["locale"] ??= "en";',
    '        $name = $this->config?->getName() ?? "unnamed";',
    '        return [$timeout, $retries, $name, $options];',
    '    }',
    '',
    '    public function legacy(array $options): array',
    '    {',
    '        // The shapes ?? replaces, still common in older code',
    '        $timeout = isset($options["timeout"]) ? $options["timeout"] : 30;',
    '        $retries = array_key_exists("retries", $options) ? $options["retries"] : null;',
    '        $locale = empty($options["locale"]) ? "en" : $options["locale"];',
    '        $name = isset($this->config) && $this->config->getName() ? $this->config->getName() : "unnamed";',
    '        return [$timeout, $retries, $locale, $name];',
    '    }',
    '}',
  ].join('\n') + '\n');
}

/** nelmio/security-bundle and pgbouncer. */
function securityBundleAndPgbouncer(root: string): void {
  put(root, 'config/packages/nelmio_security.yaml', [
    'nelmio_security:',
    '    signed_cookie:',
    '        names: ["*"]',
    '    clickjacking:',
    '        paths:',
    '            "^/.*": DENY',
    '    content_type:',
    '        nosniff: true',
    '    xss_protection:',
    '        enabled: true',
    '        mode_block: true',
    '    forced_ssl:',
    '        enabled: false',
    '        hsts_max_age: 31536000',
    '        hsts_subdomains: true',
    '    csp:',
    '        enabled: true',
    '        report_logger_service: logger',
    '        enforce:',
    '            default-src: ["\'self\'"]',
    '            script-src: ["\'self\'", "\'unsafe-inline\'"]',
    '            img-src: ["\'self\'", "data:"]',
  ].join('\n') + '\n');

  put(root, 'docker/pgbouncer/pgbouncer.ini', [
    '[databases]',
    'app = host=postgres port=5432 dbname=app',
    '',
    '[pgbouncer]',
    'listen_addr = 0.0.0.0',
    'listen_port = 6432',
    'auth_type = scram-sha-256',
    'pool_mode = transaction',
    'max_client_conn = 200',
    'default_pool_size = 20',
    'server_reset_query = DISCARD ALL',
  ].join('\n') + '\n');

  put(root, '.env.pgbouncer', 'DATABASE_URL="postgresql://app@pgbouncer:6432/app?serverVersion=16"\n');
}

/** Everything in this file. */
export function addPhpPatterns(root: string): void {
  messengerConsumers(root);
  literalConfiguration(root);
  apiDocsAndForms(root);
  channelsAndAccess(root);
  assortedPhpAndConfig(root);
  toolingConfigs(root);
  gedmoTreeAndSlug(root);
  phpunitPatterns(root);
  repeatedFields(root);
  serializerCacheAdmin(root);
  nullCoalescing(root);
  securityBundleAndPgbouncer(root);
}

/** Messenger consumption in orchestration, at the paths the analyser reads. */
function messengerConsumers(root: string): void {
  put(root, 'Makefile', [
    '.PHONY: consume consume-high consume-failed test',
    '',
    'consume:',
    '\tphp bin/console messenger:consume async --limit=10 --time-limit=3600 --memory-limit=128M',
    '',
    'consume-high:',
    '\tphp bin/console messenger:consume async_priority_high -l 100 --time-limit=900',
    '',
    'consume-failed:',
    '\tphp bin/console messenger:consume failed --limit=1',
    '',
    'consume-all:',
    '\tphp bin/console messenger:consume async async_priority_high --limit=50',
    '',
    'test:',
    '\tvendor/bin/phpunit',
  ].join('\n') + '\n');

  put(root, 'docker/supervisor/messenger.conf', [
    '[program:messenger-async]',
    'command=php /var/www/bin/console messenger:consume async --limit=10 --time-limit=3600',
    'numprocs=4',
    'process_name=%(program_name)s_%(process_num)02d',
    'autostart=true',
    'autorestart=true',
    'user=www-data',
    '',
    '[program:messenger-high]',
    'command=php /var/www/bin/console messenger:consume async_priority_high -l 100',
    'numprocs=2',
    'autorestart=unexpected',
  ].join('\n') + '\n');

  put(root, 'k8s/worker-deployment.yaml', [
    'apiVersion: apps/v1',
    'kind: Deployment',
    'metadata:',
    '    name: messenger-worker',
    'spec:',
    '    replicas: 3',
    '    template:',
    '        spec:',
    '            containers:',
    '                - name: worker',
    '                  image: acme/app:latest',
    '                  command: ["php", "bin/console", "messenger:consume", "async", "--limit=50"]',
  ].join('\n') + '\n');
}

/** ICU message format, Mercure, heredoc, kernel events, Doctrine lifecycle. */
function assortedPhpAndConfig(root: string): void {
  put(root, 'translations/messages+intl-icu.en.yaml', [
    'order.count: >-',
    '    {count, plural,',
    '        =0 {No orders}',
    '        =1 {One order}',
    '        other {# orders}',
    '    }',
    'order.status: >-',
    '    {status, select,',
    '        paid {Paid}',
    '        pending {Pending}',
    '        other {Unknown}',
    '    }',
    'order.position: >-',
    '    {pos, selectordinal,',
    '        one {#st}',
    '        two {#nd}',
    '        other {#th}',
    '    }',
    'order.due: "{date, date, long} at {date, time, short}"',
  ].join('\n') + '\n');

  put(root, 'config/packages/mercure.yaml', [
    'mercure:',
    '    hubs:',
    '        default:',
    '            url: "%env(MERCURE_URL)%"',
    '            public_url: "%env(MERCURE_PUBLIC_URL)%"',
    '            jwt:',
    '                secret: "%env(MERCURE_JWT_SECRET)%"',
    '                publish: ["*"]',
  ].join('\n') + '\n');

  put(root, 'src/Service/Publisher.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'use Symfony\\Component\\Mercure\\HubInterface;',
    'use Symfony\\Component\\Mercure\\Update;',
    '',
    'class Publisher',
    '{',
    '    public function __construct(private HubInterface $hub) {}',
    '',
    '    public function publish(array $data): void',
    '    {',
    '        $this->hub->publish(new Update("https://example.com/orders", json_encode($data)));',
    '        // Private update: only subscribers with a matching JWT receive it',
    '        $this->hub->publish(new Update("https://example.com/orders/1", "{}", private: true));',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Service/Queries.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class Queries',
    '{',
    '    public function heredoc(string $status): string',
    '    {',
    '        // Interpolating into a heredoc holding SQL',
    '        return <<<SQL',
    '            SELECT * FROM orders WHERE status = \'$status\'',
    '        SQL;',
    '    }',
    '',
    '    public function nowdoc(): string',
    '    {',
    '        return <<<\'SQL\'',
    '            SELECT * FROM orders WHERE status = :status',
    '        SQL;',
    '    }',
    '',
    '    public function html(string $name): string',
    '    {',
    '        // Unescaped interpolation into markup',
    '        return <<<HTML',
    '            <div class="user">$name</div>',
    '        HTML;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/EventSubscriber/KernelSubscriber.php', [
    '<?php',
    'namespace App\\EventSubscriber;',
    '',
    'use Symfony\\Component\\EventDispatcher\\EventSubscriberInterface;',
    'use Symfony\\Component\\HttpKernel\\Event\\RequestEvent;',
    'use Symfony\\Component\\HttpKernel\\Event\\ResponseEvent;',
    'use Symfony\\Component\\HttpKernel\\KernelEvents;',
    '',
    'class KernelSubscriber implements EventSubscriberInterface',
    '{',
    '    public static function getSubscribedEvents(): array',
    '    {',
    '        return [',
    '            KernelEvents::REQUEST => [["onRequest", 250]],',
    '            KernelEvents::RESPONSE => "onResponse",',
    '            KernelEvents::EXCEPTION => [["onException", -64]],',
    '            KernelEvents::TERMINATE => "onTerminate",',
    '        ];',
    '    }',
    '',
    '    public function onRequest(RequestEvent $event): void',
    '    {',
    '        if (!$event->isMainRequest()) { return; }',
    '    }',
    '',
    '    public function onResponse(ResponseEvent $event): void {}',
    '    public function onException($event): void {}',
    '    public function onTerminate($event): void {}',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/EventListener/OrderLifecycleListener.php', [
    '<?php',
    'namespace App\\EventListener;',
    '',
    'use Doctrine\\Bundle\\DoctrineBundle\\Attribute\\AsDoctrineListener;',
    'use Doctrine\\Bundle\\DoctrineBundle\\Attribute\\AsEntityListener;',
    'use Doctrine\\ORM\\Event\\PostPersistEventArgs;',
    'use Doctrine\\ORM\\Events;',
    '',
    '#[AsDoctrineListener(event: Events::postFlush)]',
    'class OrderLifecycleListener',
    '{',
    '    public function postFlush($args): void',
    '    {',
    '        // Flushing from inside a flush listener re-enters the unit of work',
    '        $args->getObjectManager()->flush();',
    '    }',
    '}',
    '',
    '#[AsEntityListener(event: Events::postPersist, entity: \\App\\Entity\\Order::class)]',
    'class OrderPersistListener',
    '{',
    '    public function postPersist($order, PostPersistEventArgs $args): void {}',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Entity/LifecycleOrder.php', [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    '',
    '/**',
    ' * @ORM\\Entity',
    ' * @ORM\\HasLifecycleCallbacks',
    ' */',
    '#[ORM\\Entity]',
    '#[ORM\\HasLifecycleCallbacks]',
    'class LifecycleOrder',
    '{',
    '    #[ORM\\PrePersist]',
    '    public function onPrePersist(): void {}',
    '',
    '    #[ORM\\PreUpdate]',
    '    public function onPreUpdate(): void {}',
    '',
    '    #[ORM\\PostLoad]',
    '    public function onPostLoad(): void {}',
    '}',
  ].join('\n') + '\n');
}

/** Rector, Varnish, FrankenPHP, JWT. */
function toolingConfigs(root: string): void {
  put(root, 'rector.php', [
    '<?php',
    '',
    'declare(strict_types=1);',
    '',
    'use Rector\\Config\\RectorConfig;',
    'use Rector\\Set\\ValueObject\\LevelSetList;',
    'use Rector\\Set\\ValueObject\\SetList;',
    'use Rector\\Symfony\\Set\\SymfonySetList;',
    'use Rector\\DeadCode\\Rector\\ClassMethod\\RemoveUnusedPrivateMethodRector;',
    '',
    'return RectorConfig::configure()',
    '    ->withPaths([__DIR__ . "/src", __DIR__ . "/tests"])',
    '    ->withParallel()',
    '    ->withCache(__DIR__ . "/var/rector")',
    '    ->withSets([',
    '        LevelSetList::UP_TO_PHP_83,',
    '        SetList::DEAD_CODE,',
    '        SetList::CODE_QUALITY,',
    '        SetList::TYPE_DECLARATION,',
    '        SymfonySetList::SYMFONY_64,',
    '    ])',
    '    ->withRules([RemoveUnusedPrivateMethodRector::class])',
    '    ->withSkip([__DIR__ . "/src/Migrations"]);',
  ].join('\n') + '\n');

  put(root, 'docker/varnish/default.vcl', [
    'vcl 4.1;',
    '',
    'backend default {',
    '    .host = "nginx";',
    '    .port = "80";',
    '    .probe = {',
    '        .url = "/health";',
    '        .interval = 5s;',
    '        .timeout = 2s;',
    '    }',
    '}',
    '',
    'acl purgers {',
    '    "localhost";',
    '    "10.0.0.0"/8;',
    '}',
    '',
    'sub vcl_recv {',
    '    if (req.method == "PURGE") {',
    '        if (!client.ip ~ purgers) { return (synth(405)); }',
    '        return (purge);',
    '    }',
    '    if (req.method == "BAN") {',
    '        ban("obj.http.x-url ~ " + req.http.x-ban);',
    '        return (synth(200));',
    '    }',
    '    set req.http.X-Forwarded-For = client.ip;',
    '    unset req.http.Cookie;',
    '}',
  ].join('\n') + '\n');

  put(root, 'Caddyfile', [
    '{',
    '    frankenphp',
    '    order php_server before file_server',
    '}',
    '',
    'app.example.com {',
    '    root * /app/public',
    '    encode zstd gzip',
    '    php_server',
    '    header {',
    '        X-Frame-Options DENY',
    '        X-Content-Type-Options nosniff',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/lexik_jwt_authentication.yaml', [
    'lexik_jwt_authentication:',
    '    secret_key: "%env(resolve:JWT_SECRET_KEY)%"',
    '    public_key: "%env(resolve:JWT_PUBLIC_KEY)%"',
    '    pass_phrase: "%env(JWT_PASSPHRASE)%"',
    '    token_ttl: 3600',
    '    token_extractors:',
    '        authorization_header:',
    '            enabled: true',
    '            prefix: Bearer',
    '            name: Authorization',
    '        cookie:',
    '            enabled: false',
    '    set_cookies:',
    '        BEARER:',
    '            lifetime: 3600',
    '            samesite: strict',
    '            secure: true',
    '            httpOnly: true',
  ].join('\n') + '\n');
}

/** OpenAPI attributes, XSS shapes, choice fields, generics, translatable. */
function apiDocsAndForms(root: string): void {
  put(root, 'src/Controller/DocumentedController.php', [
    '<?php',
    'namespace App\\Controller;',
    '',
    'use OpenApi\\Attributes as OA;',
    'use Symfony\\Component\\HttpFoundation\\Response;',
    'use Symfony\\Component\\Routing\\Attribute\\Route;',
    '',
    '#[OA\\Tag(name: "orders")]',
    'class DocumentedController',
    '{',
    '    #[Route("/api/orders", methods: ["GET"])]',
    '    #[OA\\Get(',
    '        path: "/api/orders",',
    '        summary: "List orders",',
    '        parameters: [new OA\\Parameter(name: "page", in: "query", schema: new OA\\Schema(type: "integer"))],',
    '        responses: [',
    '            new OA\\Response(response: 200, description: "OK"),',
    '            new OA\\Response(response: 404, description: "Not found"),',
    '        ]',
    '    )]',
    '    public function list(): Response { return new Response("[]"); }',
    '',
    '    #[Route("/api/orders", methods: ["POST"])]',
    '    #[OA\\Post(',
    '        requestBody: new OA\\RequestBody(content: new OA\\JsonContent(ref: "#/components/schemas/Order")),',
    '        responses: [new OA\\Response(response: 201, description: "Created")]',
    '    )]',
    '    public function create(): Response { return new Response("", 201); }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/ApiResource/OrderSchema.php', [
    '<?php',
    'namespace App\\ApiResource;',
    '',
    'use OpenApi\\Attributes as OA;',
    '',
    '#[OA\\Schema(schema: "Order", required: ["reference"])]',
    'class OrderSchema',
    '{',
    '    #[OA\\Property(type: "string", example: "ORD-1")]',
    '    public string $reference;',
    '',
    '    #[OA\\Property(type: "number", format: "float")]',
    '    public float $total;',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Controller/OutputController.php', [
    '<?php',
    'namespace App\\Controller;',
    '',
    'use Symfony\\Component\\HttpFoundation\\Request;',
    'use Symfony\\Component\\HttpFoundation\\Response;',
    '',
    'class OutputController',
    '{',
    '    public function render(Request $request): Response',
    '    {',
    '        $name = $request->query->get("name");',
    '',
    '        // Written to the response without escaping',
    '        echo "<div>" . $name . "</div>";',
    '        print("<span>{$name}</span>");',
    '        printf("<p>%s</p>", $name);',
    '',
    '        // The escaped counterparts',
    '        echo htmlspecialchars($name, ENT_QUOTES, "UTF-8");',
    '        echo htmlentities($name);',
    '        echo strip_tags($name);',
    '',
    '        return new Response("<b>" . $name . "</b>");',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Form/ChoiceFieldsType.php', [
    '<?php',
    'namespace App\\Form;',
    '',
    'use App\\Entity\\Category;',
    'use App\\Enum\\OrderStatus;',
    'use Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType;',
    'use Symfony\\Component\\Form\\AbstractType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\EnumType;',
    'use Symfony\\Component\\Form\\FormBuilderInterface;',
    '',
    'class ChoiceFieldsType extends AbstractType',
    '{',
    '    public function buildForm(FormBuilderInterface $builder, array $options): void',
    '    {',
    '        $builder',
    '            ->add("category", EntityType::class, [',
    '                "class" => Category::class,',
    '                "choice_label" => "name",',
    '                "choice_value" => "id",',
    '            ])',
    '            ->add("status", EnumType::class, ["class" => OrderStatus::class])',
    '            ->add("priority", ChoiceType::class, [',
    '                "choices" => ["Low" => 1, "High" => 2],',
    '                "choice_value" => fn ($choice) => $choice ? (string) $choice : "",',
    '            ]);',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Collection/TypedCollection.php', [
    '<?php',
    'namespace App\\Collection;',
    '',
    '/**',
    ' * @template T of object',
    ' * @implements \\IteratorAggregate<int, T>',
    ' */',
    'class TypedCollection implements \\IteratorAggregate',
    '{',
    '    /** @var list<T> */',
    '    private array $items = [];',
    '',
    '    /**',
    '     * @param T $item',
    '     * @phpstan-param T $item',
    '     */',
    '    public function add(object $item): void { $this->items[] = $item; }',
    '',
    '    /**',
    '     * @return \\Traversable<int, T>',
    '     * @psalm-return \\Traversable<int, T>',
    '     */',
    '    public function getIterator(): \\Traversable',
    '    {',
    '        return new \\ArrayIterator($this->items);',
    '    }',
    '}',
    '',
    '/**',
    ' * @extends TypedCollection<\\App\\Entity\\Order>',
    ' */',
    'class OrderCollection extends TypedCollection {}',
  ].join('\n') + '\n');

  put(root, 'src/Entity/TranslatableProduct.php', [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    'use Gedmo\\Mapping\\Annotation as Gedmo;',
    'use Gedmo\\Translatable\\Entity\\MappedSuperclass\\AbstractPersonalTranslation;',
    '',
    '#[ORM\\Entity]',
    'class TranslatableProduct',
    '{',
    '    /**',
    '     * @Gedmo\\Translatable',
    '     * @ORM\\Column(length=255)',
    '     */',
    '    #[Gedmo\\Translatable]',
    '    private $name;',
    '',
    '    /**',
    '     * @Gedmo\\Locale',
    '     */',
    '    #[Gedmo\\Locale]',
    '    private $locale;',
    '}',
    '',
    'class ProductTranslation extends AbstractPersonalTranslation {}',
  ].join('\n') + '\n');
}

/** Monolog channels, IP access rules, and the deprecated isMasterRequest. */
function channelsAndAccess(root: string): void {
  put(root, 'config/packages/monolog_channels.yaml', [
    'monolog:',
    '    channels: ["deprecation", "business", "security"]',
    '    handlers:',
    '        main:',
    '            type: rotating_file',
    '            path: "%kernel.logs_dir%/%kernel.environment%.log"',
    '            level: error',
    '            max_files: 10',
    '            channels: ["!event", "!doctrine"]',
    '        business:',
    '            type: stream',
    '            path: "%kernel.logs_dir%/business.log"',
    '            level: info',
    '            channels: ["business"]',
    '        security:',
    '            type: fingers_crossed',
    '            action_level: error',
    '            handler: main',
    '            channels: ["security"]',
    '        deprecation:',
    '            type: stream',
    '            path: "%kernel.logs_dir%/deprecation.log"',
    '            channels: ["deprecation"]',
  ].join('\n') + '\n');

  put(root, 'config/packages/security_ip.yaml', [
    'security:',
    '    access_control:',
    '        - { path: ^/admin, roles: ROLE_ADMIN, ips: [127.0.0.1, 10.0.0.0/8] }',
    '        - { path: ^/internal, ips: [192.168.1.0/24], roles: PUBLIC_ACCESS }',
    '        - { path: ^/metrics, ips: [::1, 127.0.0.1] }',
    '        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }',
  ].join('\n') + '\n');

  put(root, 'src/EventSubscriber/LegacyKernelSubscriber.php', [
    '<?php',
    'namespace App\\EventSubscriber;',
    '',
    'use Symfony\\Component\\EventDispatcher\\EventSubscriberInterface;',
    'use Symfony\\Component\\HttpKernel\\KernelEvents;',
    '',
    'class LegacyKernelSubscriber implements EventSubscriberInterface',
    '{',
    '    public static function getSubscribedEvents()',
    '    {',
    '        return [',
    '            KernelEvents::REQUEST => "onKernelRequest",',
    '            KernelEvents::CONTROLLER => [["onController", 0]],',
    '            KernelEvents::VIEW => "onView",',
    '            KernelEvents::FINISH_REQUEST => "onFinishRequest",',
    '        ];',
    '    }',
    '',
    '    public function onKernelRequest($event)',
    '    {',
    '        // The pre-5.3 name, deprecated but still in plenty of code',
    '        if (!$event->isMasterRequest()) {',
    '            return;',
    '        }',
    '    }',
    '',
    '    public function onController($event) {}',
    '    public function onView($event) {}',
    '    public function onFinishRequest($event) {}',
    '}',
  ].join('\n') + '\n');
}

/**
 * Literal values where the fixtures used environment placeholders.
 *
 * Several analysers classify a DSN by its scheme, or read a numeric setting
 * and compare it. `"%env(CROWDIN_DSN)%"` tells them nothing: the scheme
 * detection, the comparison and everything they guard never run. Real
 * applications hold both kinds, so the fixture now does too.
 */
function literalConfiguration(root: string): void {
  put(root, 'config/packages/translation.yaml', [
    'framework:',
    '    default_locale: en',
    '    translator:',
    '        default_path: "%kernel.project_dir%/translations"',
    '        fallbacks: [en, es]',
    '        providers:',
    '            crowdin:',
    '                dsn: "crowdin://PROJECT_ID:TOKEN@default"',
    '                domains: ["messages", "validators"]',
    '                locales: ["en", "es", "fr"]',
    '            loco:',
    '                dsn: "loco://API_KEY@default"',
    '                locales: ["en"]',
    '            lokalise:',
    '                dsn: "lokalise://PROJECT_ID:API_KEY@default"',
    '            phrase:',
    '                dsn: "phrase://PROJECT_ID:TOKEN@default?userAgent=acme"',
    '            unknown_provider:',
    '                dsn: "somevendor://token@default"',
    '            from_env:',
    '                dsn: "%env(TRANSLATION_DSN)%"',
  ].join('\n') + '\n');

  put(root, 'config/packages/rate_limiter.yaml', [
    'framework:',
    '    rate_limiter:',
    '        anonymous_api:',
    '            policy: "fixed_window"',
    '            limit: 100',
    '            interval: "60 minutes"',
    '        authenticated_api:',
    '            policy: "token_bucket"',
    '            limit: 5000',
    '            rate: { interval: "15 minutes", amount: 500 }',
    '        login_attempts:',
    '            policy: "sliding_window"',
    '            limit: 5',
    '            interval: "15 minutes"',
    '        bursty:',
    '            policy: "token_bucket"',
    '            limit: 20',
    '            rate: { interval: "1 second", amount: 20 }',
    '        unlimited:',
    '            policy: "no_limit"',
  ].join('\n') + '\n');

  put(root, 'config/packages/cache.yaml', [
    'framework:',
    '    cache:',
    '        app: cache.adapter.redis',
    '        system: cache.adapter.system',
    '        default_redis_provider: "redis://localhost:6379"',
    '        default_memcached_provider: "memcached://localhost:11211"',
    '        pools:',
    '            app.cache.products:',
    '                adapter: cache.adapter.array',
    '                default_lifetime: 3600',
    '            app.cache.chained:',
    '                adapters: ["cache.adapter.array", "cache.adapter.redis"]',
    '                default_lifetime: 60',
    '            app.cache.tagged:',
    '                adapter: cache.app',
    '                tags: true',
    '            app.cache.filesystem:',
    '                adapter: cache.adapter.filesystem',
    '                default_lifetime: 86400',
    '            doctrine.result_cache_pool:',
    '                adapter: cache.app',
  ].join('\n') + '\n');

  put(root, 'config/packages/messenger_literal.yaml', [
    'framework:',
    '    messenger:',
    '        failure_transport: failed',
    '        transports:',
    '            amqp_transport:',
    '                dsn: "amqp://guest:guest@rabbitmq:5672/%2f/messages"',
    '                retry_strategy: { max_retries: 3, delay: 1000, multiplier: 2, max_delay: 0 }',
    '            redis_transport:',
    '                dsn: "redis://redis:6379/messages/symfony/consumer"',
    '            sqs_transport:',
    '                dsn: "https://sqs.eu-west-1.amazonaws.com/0/orders.fifo"',
    '            beanstalkd_transport:',
    '                dsn: "beanstalkd://localhost:11300"',
    '            doctrine_transport:',
    '                dsn: "doctrine://default?queue_name=default"',
    '            failed:',
    '                dsn: "doctrine://default?queue_name=failed"',
  ].join('\n') + '\n');
}
