// SPDX-FileCopyrightText: 2026 Ángel Guzmán Maeso <angel@guzmanmaeso.com>
// SPDX-License-Identifier: MIT
/**
 * A third batch: name converters, IPC, locks, log formatters, DQL
 * projections, asset integrity, OpenAPI security, Cloud Run, UX icons,
 * column charsets, form events, API versions, Rector and IMAP.
 */

import * as fs from 'fs';
import * as path from 'path';

function put(root: string, rel: string, content: string): void {
  const full = path.join(root, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content);
}

function serializerAndLocks(root: string): void {
  put(root, 'src/Serializer/NameConverter/ApiNameConverter.php', [
    '<?php',
    'namespace App\\Serializer\\NameConverter;',
    '',
    'use Symfony\\Component\\Serializer\\NameConverter\\AdvancedNameConverterInterface;',
    '',
    'class ApiNameConverter implements AdvancedNameConverterInterface',
    '{',
    '    private const MAP = ["createdAt" => "created_at", "id" => "identifier"];',
    '',
    '    public function normalize(string $propertyName, ?string $class = null, ?string $format = null, array $context = []): string',
    '    {',
    '        return self::MAP[$propertyName] ?? $propertyName;',
    '    }',
    '',
    '    public function denormalize(string $propertyName, ?string $class = null, ?string $format = null, array $context = []): string',
    '    {',
    '        return array_search($propertyName, self::MAP, true) ?: $propertyName;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Serializer/NameConverter/SnakeConverter.php', [
    '<?php',
    'namespace App\\Serializer\\NameConverter;',
    '',
    'use Symfony\\Component\\Serializer\\NameConverter\\CamelCaseToSnakeCaseNameConverter;',
    'use Symfony\\Component\\Serializer\\NameConverter\\NameConverterInterface;',
    '',
    'class SnakeConverter implements NameConverterInterface',
    '{',
    '    public function __construct(private CamelCaseToSnakeCaseNameConverter $inner = new CamelCaseToSnakeCaseNameConverter()) {}',
    '',
    '    public function normalize(string $propertyName): string { return $this->inner->normalize($propertyName); }',
    '    public function denormalize(string $propertyName): string { return $this->inner->denormalize($propertyName); }',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/lock.yaml', [
    'framework:',
    '    lock:',
    '        default: "%env(LOCK_DSN)%"',
    '        invoice: "redis://redis:6379"',
    '        import: "flock"',
    '        reports: "semaphore"',
    '        legacy: "%env(DATABASE_URL)%"',
  ].join('\n') + '\n');

  put(root, 'src/Service/InvoiceLocker.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'use Symfony\\Component\\Lock\\LockFactory;',
    'use Symfony\\Component\\Lock\\LockInterface;',
    '',
    'class InvoiceLocker',
    '{',
    '    public function __construct(private LockFactory $invoiceLockFactory) {}',
    '',
    '    public function run(string $id): void',
    '    {',
    '        $lock = $this->invoiceLockFactory->createLock("invoice-" . $id, 30.0, true);',
    '        if (!$lock->acquire()) { return; }',
    '        try {',
    '            $lock->refresh();',
    '        } finally {',
    '            $lock->release();',
    '        }',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Logger/JsonLineFormatter.php', [
    '<?php',
    'namespace App\\Logger;',
    '',
    'use Monolog\\Formatter\\JsonFormatter;',
    'use Monolog\\LogRecord;',
    '',
    'class JsonLineFormatter extends JsonFormatter',
    '{',
    '    public function format(LogRecord $record): string',
    '    {',
    '        $data = $record->toArray();',
    '        unset($data["context"]["password"]);',
    '',
    '        return json_encode($data, JSON_UNESCAPED_SLASHES) . "\\n";',
    '    }',
    '',
    '    public function formatBatch(array $records): string',
    '    {',
    '        return implode("", array_map([$this, "format"], $records));',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Logger/ShortLineFormatter.php', [
    '<?php',
    'namespace App\\Logger;',
    '',
    'use Monolog\\Formatter\\FormatterInterface;',
    '',
    'class ShortLineFormatter implements FormatterInterface',
    '{',
    '    public function format($record) { return $record["message"]; }',
    '    public function formatBatch(array $records) { return implode("", $records); }',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/prod/monolog.yaml', [
    'monolog:',
    '    handlers:',
    '        main:',
    '            type: stream',
    '            path: php://stderr',
    '            level: error',
    '            formatter: App\\Logger\\JsonLineFormatter',
    '        console:',
    '            type: console',
    '            formatter: monolog.formatter.json',
    '',
    'services:',
    '    App\\Logger\\JsonLineFormatter:',
    '        arguments: [null, "Y-m-d\\\\TH:i:sP", true, true]',
  ].join('\n') + '\n');

  put(root, 'src/Service/Ipc.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class Ipc',
    '{',
    '    public function share(string $payload): void',
    '    {',
    '        $key = ftok(__FILE__, "a");',
    '        $id = shmop_open($key, "c", 0644, 1024);',
    '        shmop_write($id, $payload, 0);',
    '        $read = shmop_read($id, 0, 1024);',
    '        shmop_delete($id);',
    '',
    '        $sem = sem_get($key, 1, 0666, 1);',
    '        sem_acquire($sem);',
    '        sem_release($sem);',
    '',
    '        $queue = msg_get_queue($key, 0666);',
    '        msg_send($queue, 1, $payload, true);',
    '        msg_receive($queue, 1, $type, 1024, $message, true);',
    '        msg_remove_queue($queue);',
    '',
    '        $shm = shm_attach($key, 4096, 0666);',
    '        shm_put_var($shm, 1, $payload);',
    '        shm_get_var($shm, 1);',
    '        shm_detach($shm);',
    '    }',
    '}',
  ].join('\n') + '\n');
}

function doctrineAndApi(root: string): void {
  put(root, 'src/Repository/ArticleProjectionRepository.php', [
    '<?php',
    'namespace App\\Repository;',
    '',
    'use Doctrine\\Bundle\\DoctrineBundle\\Repository\\ServiceEntityRepository;',
    '',
    'class ArticleProjectionRepository extends ServiceEntityRepository',
    '{',
    '    public function summaries(): array',
    '    {',
    '        return $this->createQueryBuilder("a")',
    '            ->select("NEW App\\\\Dto\\\\ArticleSummary(a.title, a.slug, COUNT(c.id))")',
    '            ->leftJoin("a.comments", "c")',
    '            ->groupBy("a.id")',
    '            ->getQuery()',
    '            ->getResult();',
    '    }',
    '',
    '    public function partial(): array',
    '    {',
    '        return $this->getEntityManager()',
    '            ->createQuery("SELECT PARTIAL a.{id, title} FROM App\\\\Entity\\\\Article a")',
    '            ->getArrayResult();',
    '    }',
    '',
    '    public function scalars(): array',
    '    {',
    '        return $this->getEntityManager()',
    '            ->createQuery("SELECT a.title, a.slug FROM App\\\\Entity\\\\Article a")',
    '            ->getScalarResult();',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Entity/Invoice.php', [
    '<?php',
    'namespace App\\Entity;',
    '',
    'use Doctrine\\ORM\\Mapping as ORM;',
    '',
    '#[ORM\\Entity]',
    '#[ORM\\Table(name: "invoice", options: ["charset" => "utf8mb4", "collate" => "utf8mb4_unicode_ci"])]',
    'class Invoice',
    '{',
    '    #[ORM\\Id]',
    '    #[ORM\\GeneratedValue]',
    '    #[ORM\\Column]',
    '    private ?int $id = null;',
    '',
    '    #[ORM\\Column(type: "string", length: 32, options: ["charset" => "ascii", "collation" => "ascii_bin"])]',
    '    private string $reference = "";',
    '',
    '    #[ORM\\Column(type: "text", options: ["charset" => "utf8mb4", "collation" => "utf8mb4_general_ci"])]',
    '    private string $notes = "";',
    '',
    '    #[ORM\\Column(type: "string", length: 255)]',
    '    private string $customerName = "";',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/packages/nelmio_api_doc.yaml', [
    'nelmio_api_doc:',
    '    documentation:',
    '        info:',
    '            title: Acme API',
    '            version: 1.0.0',
    '        components:',
    '            securitySchemes:',
    '                Bearer:',
    '                    type: http',
    '                    scheme: bearer',
    '                    bearerFormat: JWT',
    '                ApiKey:',
    '                    type: apiKey',
    '                    in: header',
    '                    name: X-API-KEY',
    '                Basic:',
    '                    type: http',
    '                    scheme: basic',
    '                OAuth:',
    '                    type: oauth2',
    '                    flows:',
    '                        authorizationCode:',
    '                            authorizationUrl: https://auth.example.com/authorize',
    '                            tokenUrl: https://auth.example.com/token',
    '                            scopes:',
    '                                read: Read access',
    '        security:',
    '            - Bearer: []',
    '    areas:',
    '        path_patterns: ["^/api(?!/doc$)"]',
  ].join('\n') + '\n');

  put(root, 'src/OpenApi/SecurityFactory.php', [
    '<?php',
    'namespace App\\OpenApi;',
    '',
    'use ApiPlatform\\OpenApi\\Factory\\OpenApiFactoryInterface;',
    'use ApiPlatform\\OpenApi\\OpenApi;',
    'use ApiPlatform\\OpenApi\\Model\\SecurityScheme;',
    '',
    'final class SecurityFactory implements OpenApiFactoryInterface',
    '{',
    '    public function __construct(private OpenApiFactoryInterface $decorated) {}',
    '',
    '    public function __invoke(array $context = []): OpenApi',
    '    {',
    '        $openApi = ($this->decorated)($context);',
    '        $openApi->getComponents()->getSecuritySchemes()->offsetSet("JWT", new SecurityScheme(',
    '            type: "http",',
    '            scheme: "bearer",',
    '            bearerFormat: "JWT",',
    '        ));',
    '',
    '        return $openApi;',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'config/routes/api_versions.yaml', [
    'api_v1:',
    '    resource: ../../src/Controller/Api/V1/',
    '    type: attribute',
    '    prefix: /api/v1',
    '',
    'api_v2:',
    '    resource: ../../src/Controller/Api/V2/',
    '    type: attribute',
    '    prefix: /api/v2',
  ].join('\n') + '\n');

  put(root, 'src/Controller/Api/V1/OrderController.php', [
    '<?php',
    'namespace App\\Controller\\Api\\V1;',
    '',
    'use Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController;',
    'use Symfony\\Component\\HttpFoundation\\JsonResponse;',
    'use Symfony\\Component\\Routing\\Attribute\\Route;',
    '',
    '#[Route("/api/v1/orders")]',
    'class OrderController extends AbstractController',
    '{',
    '    #[Route("", name: "api_v1_orders", methods: ["GET"])]',
    '    public function list(): JsonResponse { return $this->json([]); }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Controller/Api/V2/OrderController.php', [
    '<?php',
    'namespace App\\Controller\\Api\\V2;',
    '',
    'use Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController;',
    'use Symfony\\Component\\HttpFoundation\\JsonResponse;',
    'use Symfony\\Component\\Routing\\Attribute\\Route;',
    '',
    '#[Route("/api/v2/orders")]',
    'class OrderController extends AbstractController',
    '{',
    '    #[Route("", name: "api_v2_orders", methods: ["GET"])]',
    '    public function list(): JsonResponse { return $this->json([]); }',
    '',
    '    #[Route("/{id}", name: "api_v2_order", methods: ["GET"])]',
    '    public function show(int $id): JsonResponse { return $this->json([]); }',
    '}',
  ].join('\n') + '\n');
}

function deploymentAndFront(root: string): void {
  put(root, 'service.yaml', [
    'apiVersion: serving.knative.dev/v1',
    'kind: Service',
    'metadata:',
    '    name: acme-app',
    '    annotations:',
    '        run.googleapis.com/ingress: all',
    'spec:',
    '    template:',
    '        metadata:',
    '            annotations:',
    '                autoscaling.knative.dev/maxScale: "100"',
    '                autoscaling.knative.dev/minScale: "0"',
    '                run.googleapis.com/cpu-throttling: "true"',
    '        spec:',
    '            containerConcurrency: 80',
    '            timeoutSeconds: 300',
    '            containers:',
    '                - image: gcr.io/acme/app:latest',
    '                  ports:',
    '                      - containerPort: 8080',
    '                  env:',
    '                      - name: APP_ENV',
    '                        value: prod',
    '                      - name: DATABASE_URL',
    '                        value: "postgresql://user:hunter2@db:5432/acme"',
    '                  resources:',
    '                      limits:',
    '                          cpu: "1"',
    '                          memory: 512Mi',
  ].join('\n') + '\n');

  put(root, 'deploy/cloudrun/staging.yaml', [
    'apiVersion: serving.knative.dev/v1',
    'kind: Service',
    'metadata:',
    '    name: acme-app-staging',
    'spec:',
    '    template:',
    '        spec:',
    '            containerConcurrency: 1',
    '            containers:',
    '                - image: gcr.io/acme/app:staging',
    '                  env:',
    '                      - name: STRIPE_SECRET',
    '                        value: "sk\x5flive_51HxYzAbCdEfGhIjKlMnOpQrStUvWxYz0123456789"',
    '                      - name: DATABASE_PASSWORD',
    '                        value: "S3cr3tP4ssw0rdF0rTh3Db"',
    '                      - name: MAILER_DSN',
    '                        valueFrom:',
    '                            secretKeyRef:',
    '                                name: mailer',
    '                                key: dsn',
    '                  resources:',
    '                      limits:',
    '                          memory: 256Mi',
  ].join('\n') + '\n');

  put(root, 'cloudbuild.yaml', [
    'steps:',
    '    - name: gcr.io/cloud-builders/docker',
    '      args: ["build", "-t", "gcr.io/acme/app:$COMMIT_SHA", "."]',
    '    - name: gcr.io/cloud-builders/gcloud',
    '      args: ["run", "deploy", "acme-app", "--image", "gcr.io/acme/app:$COMMIT_SHA", "--region", "europe-west1", "--allow-unauthenticated"]',
    'images: ["gcr.io/acme/app:$COMMIT_SHA"]',
  ].join('\n') + '\n');

  put(root, 'rector.php', [
    '<?php',
    '',
    'declare(strict_types=1);',
    '',
    'use Rector\\Config\\RectorConfig;',
    'use Rector\\Set\\ValueObject\\LevelSetList;',
    'use Rector\\Set\\ValueObject\\SetList;',
    'use Rector\\Symfony\\Set\\SymfonySetList;',
    'use Rector\\Doctrine\\Set\\DoctrineSetList;',
    'use Rector\\PHPUnit\\Set\\PHPUnitSetList;',
    '',
    'return static function (RectorConfig $rectorConfig): void {',
    '    $rectorConfig->paths([__DIR__ . "/src", __DIR__ . "/tests"]);',
    '    $rectorConfig->skip([__DIR__ . "/src/Migrations"]);',
    '',
    '    $rectorConfig->sets([',
    '        LevelSetList::UP_TO_PHP_82,',
    '        SetList::CODE_QUALITY,',
    '        SetList::DEAD_CODE,',
    '        SetList::TYPE_DECLARATION,',
    '        SymfonySetList::SYMFONY_64,',
    '        SymfonySetList::SYMFONY_CODE_QUALITY,',
    '        SymfonySetList::ANNOTATIONS_TO_ATTRIBUTES,',
    '        DoctrineSetList::DOCTRINE_CODE_QUALITY,',
    '        PHPUnitSetList::PHPUNIT_100,',
    '    ]);',
    '',
    '    $rectorConfig->importNames();',
    '    $rectorConfig->parallel(120, 8, 10);',
    '};',
  ].join('\n') + '\n');

  put(root, 'config/packages/ux_icons.yaml', [
    'ux_icons:',
    '    icon_dir: "%kernel.project_dir%/assets/icons"',
    '    default_icon_attributes:',
    '        fill: currentColor',
    '        aria-hidden: true',
    '    iconsets:',
    '        lucide:',
    '            prefix: lucide',
    '    aliases:',
    '        cart: lucide:shopping-cart',
  ].join('\n') + '\n');

  put(root, 'assets/icons/logo.svg', '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M0 0h24v24H0z"/></svg>\n');

  put(root, 'templates/layout/header.html.twig', [
    '<header>',
    '    {{ ux_icon("logo", {class: "h-6 w-6"}) }}',
    '    {{ ux_icon("lucide:shopping-cart") }}',
    '    <twig:ux:icon name="cart" class="h-4 w-4" />',
    '    {{ ux_icon(dynamicName) }}',
    '</header>',
  ].join('\n') + '\n');

  put(root, 'templates/base.html.twig', [
    '<!DOCTYPE html>',
    '<html>',
    '    <head>',
    '        <title>{% block title %}Acme{% endblock %}</title>',
    '        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">',
    '        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter" integrity="sha384-abc123" crossorigin="anonymous">',
    '        <script src="https://cdn.jsdelivr.net/npm/htmx.org@1.9.10/dist/htmx.min.js"></script>',
    '        <script src="https://unpkg.com/alpinejs@3.13.3/dist/cdn.min.js" integrity="sha384-def456" crossorigin="anonymous" defer></script>',
    '        {{ importmap("app") }}',
    '    </head>',
    '    <body>{% block body %}{% endblock %}</body>',
    '</html>',
  ].join('\n') + '\n');

  put(root, 'src/Form/EventfulType.php', [
    '<?php',
    'namespace App\\Form;',
    '',
    'use Symfony\\Component\\Form\\AbstractType;',
    'use Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType;',
    'use Symfony\\Component\\Form\\FormBuilderInterface;',
    'use Symfony\\Component\\Form\\FormEvent;',
    'use Symfony\\Component\\Form\\FormEvents;',
    '',
    'class EventfulType extends AbstractType',
    '{',
    '    public function buildForm(FormBuilderInterface $builder, array $options): void',
    '    {',
    '        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {',
    '            $data = $event->getData();',
    '            $form = $event->getForm();',
    '            $form->add("country", ChoiceType::class, ["choices" => $data->getCountries()]);',
    '        });',
    '',
    '        $builder->addEventListener(FormEvents::POST_SET_DATA, function (FormEvent $event) {',
    '            $event->getForm()->add("region", ChoiceType::class);',
    '        });',
    '',
    '        $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {',
    '            $data = $event->getData();',
    '            $data["email"] = strtolower($data["email"]);',
    '            $event->setData($data);',
    '        });',
    '',
    '        $builder->addEventListener(FormEvents::SUBMIT, function (FormEvent $event) {',
    '            foreach ($event->getData()->getItems() as $item) {',
    '                $this->repository->find($item->getId());',
    '            }',
    '        });',
    '    }',
    '}',
  ].join('\n') + '\n');

  put(root, 'src/Service/MailFetcher.php', [
    '<?php',
    'namespace App\\Service;',
    '',
    'class MailFetcher',
    '{',
    '    public function fetch(string $user, string $password): array',
    '    {',
    '        $mbox = imap_open("{mail.example.com:143/imap}INBOX", $user, $password);',
    '        $count = imap_num_msg($mbox);',
    '        $headers = imap_headers($mbox);',
    '        $body = imap_body($mbox, 1);',
    '        $search = imap_search($mbox, "FROM \\"" . $_GET["from"] . "\\"");',
    '        imap_close($mbox);',
    '',
    '        return [$count, $headers, $body, $search];',
    '    }',
    '}',
  ].join('\n') + '\n');
}

/** Everything in this file. */
export function addBatchThree(root: string): void {
  serializerAndLocks(root);
  doctrineAndApi(root);
  deploymentAndFront(root);
}
