// SPDX-FileCopyrightText: 2026 Ángel Guzmán Maeso <angel@guzmanmaeso.com>
// SPDX-License-Identifier: MIT
/**
 * Tool category definitions and name-based classification rules.
 *
 * Categories are assigned at ToolRegistry init time by matching tool names
 * against priority-ordered keyword rules. First match wins; 'symfony-core'
 * is the fallback for anything unmatched.
 */

export type ToolCategory =
  | 'symfony-core'
  | 'database'
  | 'config'
  | 'messaging'
  | 'api'
  | 'frontend'
  | 'security'
  | 'testing'
  | 'code-quality'
  | 'infrastructure'
  | 'cloud-aws'
  | 'cloud-other'
  | 'integrations'
  | 'queues'
  | 'serializer'
  | 'cache-sessions'
  | 'discovery';

export const CATEGORY_DESCRIPTIONS: Record<ToolCategory, string> = {
  'symfony-core':   'Routes, services, controllers, events, commands, bundles, DI container, kernel',
  'database':       'Entities, migrations, Doctrine ORM, relationships, query patterns, indexes, DBAL',
  'config':         'Environment config, framework settings, Monolog, CORS, locale, feature flags',
  'messaging':      'Messenger, notifier, webhooks, Mercure, mailer, transports, stamps, failure handling',
  'api':            'API Platform, OpenAPI, GraphQL, REST patterns, versioning, rate limits, Nelmio',
  'frontend':       'Twig, translations, asset mapper, Symfony UX, Turbo, live components, Webpack',
  'security':       'Voters, firewalls, authenticators, JWT, OAuth, CSRF, access control, secrets vault',
  'testing':        'PHPUnit, Behat, Cypress, Playwright, Psalm, PHPStan, Rector, static analysis',
  'code-quality':   'Profiler, dead code detection, dependency graph, accessibility, code metrics',
  'infrastructure': 'Docker, CI/CD, Kubernetes, Terraform, Helm, Nginx, serverless, cloud platforms',
  'cloud-aws':      'AWS S3, SES, Cognito, ECS, Lambda/Bref, Parameter Store, Secrets Manager, CloudFront',
  'cloud-other':    'Azure Blob/Pipelines, Google Cloud Run/Storage, Firebase, DigitalOcean, Consul',
  'integrations':   'Stripe, Slack, Sentry, Elasticsearch, Twilio, SendGrid, Mailgun, Datadog, OpenAI',
  'queues':         'RabbitMQ, Kafka, SQS FIFO/DLQ, Pusher, Redis pub/sub and streams',
  'serializer':     'Serializer, validation, forms, constraints, DTOs, transformers, normalizers',
  'cache-sessions': 'Cache pools, HTTP cache, sessions, rate limiter, lock, cache warmers, OPcache',
  'discovery':      'Meta-tools for discovering and activating tool categories (always available)',
};

export const CATEGORY_TAGS: Record<ToolCategory, string[]> = {
  'symfony-core':   ['route', 'service', 'controller', 'event', 'command', 'bundle', 'kernel', 'di', 'container'],
  'database':       ['entity', 'doctrine', 'migration', 'dbal', 'orm', 'query', 'relationship'],
  'config':         ['environment', 'config', 'monolog', 'cors', 'locale', 'feature flag'],
  'messaging':      ['messenger', 'notifier', 'webhook', 'mercure', 'mailer', 'transport', 'queue'],
  'api':            ['api platform', 'openapi', 'graphql', 'rest', 'versioning', 'rate limit'],
  'frontend':       ['twig', 'template', 'translation', 'asset', 'ux', 'webpack', 'turbo'],
  'security':       ['voter', 'firewall', 'jwt', 'oauth', 'csrf', 'access control', 'secret'],
  'testing':        ['phpunit', 'behat', 'cypress', 'playwright', 'psalm', 'phpstan', 'rector'],
  'code-quality':   ['profiler', 'dead code', 'dependency', 'accessibility', 'complexity'],
  'infrastructure': ['docker', 'kubernetes', 'terraform', 'ci/cd', 'nginx', 'serverless'],
  'cloud-aws':      ['aws', 's3', 'lambda', 'ecs', 'cloudwatch', 'cloudfront', 'cognito'],
  'cloud-other':    ['azure', 'google cloud', 'firebase', 'digitalocean'],
  'integrations':   ['stripe', 'slack', 'sentry', 'elasticsearch', 'datadog', 'sendgrid'],
  'queues':         ['rabbitmq', 'kafka', 'sqs', 'redis pubsub', 'pusher'],
  'serializer':     ['serializer', 'validation', 'form', 'constraint', 'dto', 'normalizer'],
  'cache-sessions': ['cache', 'session', 'rate limiter', 'lock', 'opcache', 'memcached'],
  'discovery':      ['search', 'discover', 'activate', 'category', 'meta'],
};

// Priority-ordered keyword rules. Each entry is [keyword_substring, category].
// Tool names are checked in order; first match wins. 'symfony-core' is the fallback.
//
// Ordering principles:
//  1. Specific multi-word patterns before short generic ones
//  2. Cloud/vendor patterns before generic equivalents
//  3. PHP security patterns as a group before general symfony security
//  4. API Platform before generic 'api'
//  5. Testing frameworks before generic patterns
const KEYWORD_RULES: Array<[string, ToolCategory]> = [
  // ── Discovery (internal meta-tools only) ────────────────────────────────
  ['search_tools',          'discovery'],
  ['list_tool_categories',  'discovery'],
  ['activate_category',     'discovery'],
  ['get_active_tools',      'discovery'],
  ['deactivate_category',   'discovery'],

  // ── AWS Cloud ────────────────────────────────────────────────────────────
  ['aws_s3',               'cloud-aws'],
  ['aws_ses',              'cloud-aws'],
  ['aws_cognito',          'cloud-aws'],
  ['aws_ecs',              'cloud-aws'],
  ['aws_lambda',           'cloud-aws'],
  ['aws_cloudfront',       'cloud-aws'],
  ['aws_parameter',        'cloud-aws'],
  ['aws_secrets_manager',  'cloud-aws'],
  ['cloudwatch',           'cloud-aws'],
  ['aws_',                 'cloud-aws'],

  // ── Other Cloud ──────────────────────────────────────────────────────────
  ['azure_blob',           'cloud-other'],
  ['azure_pipeline',       'cloud-other'],
  ['google_cloud',         'cloud-other'],
  ['google_oauth',         'cloud-other'],
  ['google_cloud_storage', 'cloud-other'],
  ['firebase',             'cloud-other'],
  ['digital_ocean',        'cloud-other'],
  ['consul_service',       'cloud-other'],
  ['vault_dynamic',        'cloud-other'],

  // ── Queues (before integrations catches kafka/rabbitmq broadly) ──────────
  ['sqs_fifo',             'queues'],
  ['sqs_dlq',              'queues'],
  ['redis_pubsub',         'queues'],
  ['redis_stream',         'queues'],
  ['kafka_schema_registry','queues'],
  ['rabbitmq_management',  'queues'],
  ['in_memory_transport',  'queues'],

  // ── Infrastructure ───────────────────────────────────────────────────────
  ['docker_compose_health','infrastructure'],
  ['docker_security',      'infrastructure'],
  ['docker_swarm',         'infrastructure'],
  ['kubernetes_manifests', 'infrastructure'],
  ['kubernetes_config',    'infrastructure'],
  ['helm_chart',           'infrastructure'],
  ['terraform_config',     'infrastructure'],
  ['traefik_config',       'infrastructure'],
  ['caddy_server',         'infrastructure'],
  ['nginx_phpfpm',         'infrastructure'],
  ['nginx_unit',           'infrastructure'],
  ['frankenphp',           'infrastructure'],
  ['swoole',               'infrastructure'],
  ['roadrunner',           'infrastructure'],
  ['fly_io',               'infrastructure'],
  ['heroku_config',        'infrastructure'],
  ['circle_ci',            'infrastructure'],
  ['jenkins_config',       'infrastructure'],
  ['vercel_deploy',        'infrastructure'],
  ['render_deploy',        'infrastructure'],
  ['netlify_deploy',       'infrastructure'],
  ['bitbucket_pipeline',   'infrastructure'],
  ['github_actions',       'infrastructure'],
  ['gitlab_ci',            'infrastructure'],
  ['cloudflare_config',    'infrastructure'],
  ['docker_',              'infrastructure'],
  ['loki_log',             'infrastructure'],
  ['varnish_config',       'infrastructure'],
  ['cdn_config',           'infrastructure'],
  ['webserver_config',     'infrastructure'],
  ['apache_config',        'infrastructure'],
  ['grpc_integration',     'infrastructure'],
  ['pgbouncer_config',     'infrastructure'],
  ['prometheus_alerting',  'infrastructure'],
  ['sonarqube_config',     'infrastructure'],
  ['deptrac_config',       'infrastructure'],
  ['php_arkitect',         'infrastructure'],

  // ── Testing ──────────────────────────────────────────────────────────────
  ['phpunit_',             'testing'],
  ['behat_',               'testing'],
  ['cypress_',             'testing'],
  ['playwright_',          'testing'],
  ['psalm_config',         'testing'],
  ['phpstan_',             'testing'],
  ['rector_config',        'testing'],
  ['rector_custom',        'testing'],
  ['php_rector_upgrade',   'testing'],
  ['cs_fixer',             'testing'],
  ['easy_coding_standard', 'testing'],
  ['psr_compliance',       'testing'],
  ['static_analysis',      'testing'],
  ['type_coverage',        'testing'],
  ['phpbench',             'testing'],
  ['grumphp',              'testing'],
  ['phpmd',                'testing'],
  ['infection_mutant',     'testing'],
  ['panther_testing',      'testing'],
  ['zenstruck_foundry',    'testing'],
  ['phpspec_config',       'testing'],
  ['codeception_config',   'testing'],
  ['owasp_dependency',     'testing'],
  ['github_dependabot',    'testing'],
  ['constraint_validator_test', 'testing'],
  ['php_cognitive_complexity',  'testing'],
  ['php_copy_paste',       'testing'],
  ['php_covariance',       'testing'],
  ['php_magic_method',     'testing'],
  ['php_contract_test',    'testing'],
  ['abstract_pattern',     'testing'],
  ['interface_segregation','testing'],
  ['static_analysis_ignore','testing'],
  ['pest_php',             'testing'],
  ['list_test_class',      'testing'],
  ['get_test_coverage',    'testing'],
  ['get_test_stat',        'testing'],
  ['list_phpunit',         'testing'],
  ['list_psalm',           'testing'],
  ['list_phpstan',         'testing'],
  ['list_behat',           'testing'],
  ['list_phpspec',         'testing'],
  ['list_codeception',     'testing'],
  ['list_panther',         'testing'],
  ['profiler_storage',     'testing'],
  ['debug_dump',           'testing'],

  // ── PHP security vulnerability patterns (before generic security) ────────
  ['php_command_injection',          'security'],
  ['php_ssrf',                       'security'],
  ['php_open_redirect',              'security'],
  ['php_xss_patterns',               'security'],
  ['php_timing_attack',              'security'],
  ['php_null_byte',                  'security'],
  ['php_file_upload_validation',     'security'],
  ['php_deserialization',            'security'],
  ['php_regex_injection',            'security'],
  ['php_hash_algorithm',             'security'],
  ['php_template_injection',         'security'],
  ['php_object_injection',           'security'],
  ['php_curl_security',              'security'],
  ['php_xml_security',               'security'],
  ['php_ldap_function',              'security'],
  ['php_session_security',           'security'],
  ['php_file_inclusion_security',    'security'],
  ['php_string_interpolation_security', 'security'],
  ['php_pcre_security',              'security'],
  ['php_random_security',            'security'],
  ['php_openssl_patterns',           'security'],
  ['cookie_security',                'security'],
  ['csp_',                           'security'],
  ['http_security_header',           'security'],
  ['gdpr_compliance',                'security'],
  ['security_audit_log',             'security'],
  ['php_output_buffering',           'security'],

  // ── Symfony/general security ─────────────────────────────────────────────
  ['security_voter',        'security'],
  ['list_voter',            'security'],
  ['get_voter',             'security'],
  ['list_firewall',         'security'],
  ['get_firewall',          'security'],
  ['security_firewall',     'security'],
  ['security_scan',         'security'],
  ['security_passport',     'security'],
  ['security_bruteforce',   'security'],
  ['security_custom_voter', 'security'],
  ['security_entry_point',  'security'],
  ['security_post_auth',    'security'],
  ['firewall_listener',     'security'],
  ['controller_security',   'security'],
  ['audit_controller',      'security'],
  ['jwt_',                  'security'],
  ['get_jwt',               'security'],
  ['oauth_',                'security'],
  ['list_oauth',            'security'],
  ['get_oauth',             'security'],
  ['csrf_',                 'security'],
  ['list_csrf',             'security'],
  ['role_hierarchy',        'security'],
  ['list_role_hierarchy',   'security'],
  ['access_control',        'security'],
  ['list_access_control',   'security'],
  ['token_storage',         'security'],
  ['list_token_storage',    'security'],
  ['password_hash',         'security'],
  ['list_password_hash',    'security'],
  ['html_sanitizer',        'security'],
  ['list_html_sanitizer',   'security'],
  ['api_key_rotation',      'security'],
  ['vault_integration',     'security'],
  ['list_secrets',          'security'],
  ['get_secrets',           'security'],
  ['remember_me',           'security'],
  ['impersonation',         'security'],
  ['access_decision',       'security'],
  ['login_throttle',        'security'],
  ['login_link',            'security'],
  ['password_upgrade',      'security'],
  ['password_strength',     'security'],
  ['password_migration',    'security'],
  ['session_strategy',      'security'],
  ['two_factor',            'security'],
  ['live_component_security','security'],
  ['health_endpoint_security','security'],
  ['webhook_security',      'security'],
  ['secrets_rotation',      'security'],
  ['oidc_',                 'security'],
  ['access_token_',         'security'],
  ['saml_auth',             'security'],
  ['nelmio_security',       'security'],
  ['security_ip_access',    'security'],
  ['custom_voter',          'security'],
  ['get_role_hierarchy',    'security'],
  ['get_access_control',    'security'],
  ['get_security_config',   'security'],

  // ── API Platform & REST API ───────────────────────────────────────────────
  ['api_platform_',         'api'],
  ['list_api_resource',     'api'],
  ['get_api_resource',      'api'],
  ['get_api_platform',      'api'],
  ['api_state_',            'api'],
  ['list_api_state',        'api'],
  ['api_iri_',              'api'],
  ['list_api_filter',       'api'],
  ['get_api_filter',        'api'],
  ['api_pagination_',       'api'],
  ['list_api_pagination',   'api'],
  ['api_versioning',        'api'],
  ['list_api_version',      'api'],
  ['api_rate_limit',        'api'],
  ['list_api_rate',         'api'],
  ['api_hateoas',           'api'],
  ['api_jsonapi_format',    'api'],
  ['api_json_ld',           'api'],
  ['api_problem_details',   'api'],
  ['api_contract_testing',  'api'],
  ['api_cursor_pagination', 'api'],
  ['api_idempotency',       'api'],
  ['api_response_compress', 'api'],
  ['api_graphql_security',  'api'],
  ['api_custom_normalizer', 'api'],
  ['api_subresource',       'api'],
  ['api_dto_output',        'api'],
  ['api_query_extension',   'api'],
  ['api_security_expression','api'],
  ['api_openapi_security',  'api'],
  ['api_openapi_context',   'api'],
  ['api_operation_',        'api'],
  ['list_api_operation',    'api'],
  ['get_api_operation',     'api'],
  ['fos_rest',              'api'],
  ['openapi_',              'api'],
  ['list_openapi',          'api'],
  ['get_openapi',           'api'],
  ['graphql_',              'api'],
  ['list_graphql',          'api'],
  ['get_graphql',           'api'],
  ['nelmio_api_doc',        'api'],
  ['list_nelmio',           'api'],
  ['get_nelmio',            'api'],

  // ── Messaging ────────────────────────────────────────────────────────────
  ['list_messenger',        'messaging'],
  ['get_messenger',         'messaging'],
  ['messenger_',            'messaging'],
  ['message_bus',           'messaging'],
  ['list_message_bus',      'messaging'],
  ['list_message_class',    'messaging'],
  ['list_notifier',         'messaging'],
  ['get_notifier',          'messaging'],
  ['notifier_',             'messaging'],
  ['list_webhook',          'messaging'],
  ['get_webhook',           'messaging'],
  ['webhook_',              'messaging'],
  ['list_mercure',          'messaging'],
  ['get_mercure',           'messaging'],
  ['mercure_',              'messaging'],
  ['list_email_class',      'messaging'],
  ['list_email_template',   'messaging'],
  ['mailer_stat',           'messaging'],
  ['mailer_event',          'messaging'],
  ['mailer_transport',      'messaging'],
  ['mailer_dsn',            'messaging'],
  ['list_mailer',           'messaging'],
  ['get_mailer',            'messaging'],
  ['dispatch_after',        'messaging'],
  ['in_memory_transport',   'messaging'],

  // ── Frontend ─────────────────────────────────────────────────────────────
  ['list_template',         'frontend'],
  ['search_template',       'frontend'],
  ['get_template',          'frontend'],
  ['list_twig',             'frontend'],
  ['search_twig',           'frontend'],
  ['twig_',                 'frontend'],
  ['list_translation',      'frontend'],
  ['search_translation',    'frontend'],
  ['get_translation',       'frontend'],
  ['find_missing_translation','frontend'],
  ['get_translation_stat',  'frontend'],
  ['translation_',          'frontend'],
  ['list_asset',            'frontend'],
  ['get_asset',             'frontend'],
  ['asset_mapper',          'frontend'],
  ['asset_versioning',      'frontend'],
  ['asset_preload',         'frontend'],
  ['asset_integrity',       'frontend'],
  ['asset_package',         'frontend'],
  ['asset_mapper_ext',      'frontend'],
  ['list_webpack',          'frontend'],
  ['get_webpack',           'frontend'],
  ['webpack_',              'frontend'],
  ['list_stimulus',         'frontend'],
  ['stimulus_',             'frontend'],
  ['list_ux',               'frontend'],
  ['ux_',                   'frontend'],
  ['list_live_component',   'frontend'],
  ['live_component',        'frontend'],
  ['list_turbo',            'frontend'],
  ['turbo_',                'frontend'],
  ['flash_message',         'frontend'],
  ['multi_language_routing','frontend'],
  ['icu_translation',       'frontend'],
  ['xliff_format',          'frontend'],
  ['importmap',             'frontend'],
  ['pwa_manifest',          'frontend'],
  ['htmx_integration',      'frontend'],
  ['alpine_js',             'frontend'],
  ['list_alpine',           'frontend'],
  ['translation_domain',    'frontend'],

  // ── Serializer / Forms / Validation ─────────────────────────────────────
  ['list_form',             'serializer'],
  ['search_form',           'serializer'],
  ['get_form',              'serializer'],
  ['list_form_type',        'serializer'],
  ['get_form_type',         'serializer'],
  ['form_stat',             'serializer'],
  ['form_type_',            'serializer'],
  ['form_event',            'serializer'],
  ['form_transformer',      'serializer'],
  ['choice_loader',         'serializer'],
  ['form_collection',       'serializer'],
  ['form_theme',            'serializer'],
  ['form_button',           'serializer'],
  ['form_data',             'serializer'],
  ['form_repeated',         'serializer'],
  ['form_callback',         'serializer'],
  ['form_honeypot',         'serializer'],
  ['form_ajax',             'serializer'],
  ['form_compound',         'serializer'],
  ['form_data_mapper',      'serializer'],
  ['form_pre_set_data',     'serializer'],
  ['form_type_guesser',     'serializer'],
  ['list_serializer',       'serializer'],
  ['search_serializer',     'serializer'],
  ['get_serializer',        'serializer'],
  ['serializer_',           'serializer'],
  ['list_validation',       'serializer'],
  ['get_validation',        'serializer'],
  ['validation_constraint', 'serializer'],
  ['list_input_dto',        'serializer'],
  ['get_input_dto',         'serializer'],
  ['input_dto',             'serializer'],
  ['validator_',            'serializer'],
  ['object_normalizer',     'serializer'],
  ['list_custom_constraint','serializer'],
  ['custom_constraint',     'serializer'],
  ['compound_constraint',   'serializer'],
  ['file_upload',           'serializer'],
  ['validation_group',      'serializer'],
  ['serializer_group',      'serializer'],

  // ── Cache & Sessions ─────────────────────────────────────────────────────
  ['list_cache_pool',       'cache-sessions'],
  ['get_cache_pool',        'cache-sessions'],
  ['cache_pool',            'cache-sessions'],
  ['list_cache_warmer',     'cache-sessions'],
  ['cache_warmer',          'cache-sessions'],
  ['list_cache_tag',        'cache-sessions'],
  ['cache_tag',             'cache-sessions'],
  ['inspect_symfony_cache', 'cache-sessions'],
  ['inspect_mcp_cache',     'cache-sessions'],
  ['get_cache_config',      'cache-sessions'],
  ['clear_mcp_cache',       'cache-sessions'],
  ['list_http_cache',       'cache-sessions'],
  ['get_http_cache',        'cache-sessions'],
  ['http_cache',            'cache-sessions'],
  ['response_cache',        'cache-sessions'],
  ['list_session_config',   'cache-sessions'],
  ['get_session_config',    'cache-sessions'],
  ['session_config',        'cache-sessions'],
  ['list_session_handler',  'cache-sessions'],
  ['session_handler',       'cache-sessions'],
  ['list_rate_limiter',     'cache-sessions'],
  ['get_rate_limiter',      'cache-sessions'],
  ['rate_limiter',          'cache-sessions'],
  ['list_lock_config',      'cache-sessions'],
  ['get_lock_config',       'cache-sessions'],
  ['list_lock_resource',    'cache-sessions'],
  ['lock_resource',         'cache-sessions'],
  ['lock_config',           'cache-sessions'],
  ['lock_store',            'cache-sessions'],
  ['cache_chain',           'cache-sessions'],
  ['cache_redis_cluster',   'cache-sessions'],
  ['cache_redis_sentinel',  'cache-sessions'],
  ['cache_invalidation',    'cache-sessions'],
  ['cache_psr',             'cache-sessions'],
  ['cache_namespace',       'cache-sessions'],
  ['cache_early_expiry',    'cache-sessions'],
  ['cache_stampede',        'cache-sessions'],
  ['cache_pool_prune',      'cache-sessions'],
  ['opcache',               'cache-sessions'],
  ['php_opcache',           'cache-sessions'],
  ['symfony_http_cache_store','cache-sessions'],
  ['memcached',             'cache-sessions'],
  ['rate_limiter_storage',  'cache-sessions'],
  ['rate_limiter_policy',   'cache-sessions'],
  ['rate_limiter_algorithm','cache-sessions'],

  // ── Code Quality ─────────────────────────────────────────────────────────
  ['list_profiler',         'code-quality'],
  ['get_profiler',          'code-quality'],
  ['get_code_quality',      'code-quality'],
  ['get_god_class',         'code-quality'],
  ['code_quality',          'code-quality'],
  ['dead_code',             'code-quality'],
  ['dependency_graph',      'code-quality'],
  ['circular_dependency',   'code-quality'],
  ['detect_n_plus',         'code-quality'],
  ['n_plus_one',            'code-quality'],
  ['accessibility',         'code-quality'],
  ['enlighten_analysis',    'code-quality'],
  ['detect_orphan',         'code-quality'],
  ['detect_unused',         'code-quality'],
  ['get_repository_detail', 'code-quality'],
  ['get_repository_stat',   'code-quality'],
  ['list_repository',       'code-quality'],
  ['profiler_panel',        'code-quality'],
  ['debug_artifact',        'code-quality'],

  // ── Database / Doctrine ──────────────────────────────────────────────────
  ['list_entities',         'database'],
  ['get_entity',            'database'],
  ['search_entities',       'database'],
  ['get_related_entity',    'database'],
  ['get_entities_stat',     'database'],
  ['list_tables',           'database'],
  ['get_table',             'database'],
  ['get_database_info',     'database'],
  ['get_migration_status',  'database'],
  ['validate_schema',       'database'],
  ['list_migration',        'database'],
  ['get_migration',         'database'],
  ['analyze_migration',     'database'],
  ['get_destructive',       'database'],
  ['list_fixture',          'database'],
  ['get_fixture',           'database'],
  ['fixture_',              'database'],
  ['list_doctrine',         'database'],
  ['get_doctrine',          'database'],
  ['doctrine_',             'database'],
  ['dbal_',                 'database'],
  ['list_dbal',             'database'],
  ['get_dbal',              'database'],
  ['get_dql',               'database'],
  ['list_dql',              'database'],
  ['list_entity_lifecycle', 'database'],
  ['get_lifecycle',         'database'],
  ['list_embeddable',       'database'],
  ['get_embeddable',        'database'],
  ['list_doctrine_slc',     'database'],
  ['list_repository_pattern','database'],
  ['get_repository_pattern','database'],
  ['list_event_subscriber', 'database'],
  ['get_event_subscriber',  'database'],
  ['list_fetch_mode',       'database'],
  ['get_fetch_mode',        'database'],
  ['mongodb_integration',   'database'],

  // ── Config ───────────────────────────────────────────────────────────────
  ['list_env_file',         'config'],
  ['diff_env',              'config'],
  ['find_sensitive',        'config'],
  ['get_env_stat',          'config'],
  ['list_env_config',       'config'],
  ['get_env_config',        'config'],
  ['get_env_config_diff',   'config'],
  ['list_env_config_diff',  'config'],
  ['list_env_processor',    'config'],
  ['list_env_override',     'config'],
  ['list_monolog',          'config'],
  ['get_monolog',           'config'],
  ['list_cors',             'config'],
  ['get_cors',              'config'],
  ['list_locale',           'config'],
  ['get_locale',            'config'],
  ['list_feature_flag',     'config'],
  ['get_feature_flag',      'config'],
  ['get_app_environment',   'config'],
  ['list_environment_variable','config'],
  ['get_environment_log',   'config'],
  ['list_config_package',   'config'],
  ['get_framework_config',  'config'],
  ['get_services_config',   'config'],
  ['list_data_collector',   'config'],
  ['get_data_collector',    'config'],
  ['maintenance_mode',      'config'],
  ['trusted_proxy_config',  'config'],
  ['list_trusted_proxy',    'config'],
  ['get_trusted_proxy',     'config'],
  ['list_env_config_override','config'],
  ['monolog_processor',     'config'],
  ['monolog_channel',       'config'],
  ['monolog_rotation',      'config'],
  ['list_monolog_processor','config'],
  ['get_monolog_formatter', 'config'],
  ['list_monolog_channel',  'config'],

  // ── Integrations (catch-all for third-party services) ───────────────────
  ['stripe_',               'integrations'],
  ['paypal_',               'integrations'],
  ['braintree_',            'integrations'],
  ['slack_webhook',         'integrations'],
  ['twilio_',               'integrations'],
  ['sendgrid_',             'integrations'],
  ['mailgun_',              'integrations'],
  ['shopify_',              'integrations'],
  ['openai_',               'integrations'],
  ['bugsnag_',              'integrations'],
  ['new_relic',             'integrations'],
  ['newrelic_',             'integrations'],
  ['elastic_apm',           'integrations'],
  ['hubspot_',              'integrations'],
  ['cloudinary_',           'integrations'],
  ['microsoft_graph',       'integrations'],
  ['meilisearch_',          'integrations'],
  ['prometheus_metrics',    'integrations'],
  ['grafana_dashboard',     'integrations'],
  ['open_telemetry',        'integrations'],
  ['web_authn',             'integrations'],
  ['oauth2_server',         'integrations'],
  ['league_oauth2',         'integrations'],
  ['pdf_generation',        'integrations'],
  ['image_processing',      'integrations'],
  ['excel_generation',      'integrations'],
  ['file_archive',          'integrations'],
  ['segment_analytics',     'integrations'],
  ['zendesk_',              'integrations'],
  ['intercom_',             'integrations'],
  ['algolia_',              'integrations'],
  ['elasticsearch_',        'integrations'],
  ['sentry_',               'integrations'],
  ['blackfire_',            'integrations'],
  ['pusher_',               'integrations'],
  ['kafka_integration',     'integrations'],
  ['rabbitmq_config',       'integrations'],
  ['redis_config',          'integrations'],
  ['sqs_messenger',         'integrations'],
  ['datadog_',              'integrations'],
  ['easyadmin',             'integrations'],
  ['easy_admin',            'integrations'],
  ['search_integration',    'integrations'],
  ['list_http_client',      'integrations'],
  ['get_http_client',       'integrations'],
  ['http_client',           'integrations'],
  ['httpclient',            'integrations'],
  ['list_mailer_config',    'integrations'],
  ['list_file_storage',     'integrations'],
  ['file_storage',          'integrations'],
  ['clock_config',          'integrations'],
  ['get_clock',             'integrations'],
  ['list_clock',            'integrations'],
  ['list_email',            'integrations'],
  ['get_email',             'integrations'],
];

export function categorizeToolName(name: string): ToolCategory {
  for (const [keyword, category] of KEYWORD_RULES) {
    if (name.includes(keyword)) return category;
  }
  return 'symfony-core';
}
